"use strict";
const T=THREE,canvas=document.querySelector("#game"),ui=Object.fromEntries(["score","coins","multi","missionText","missionBar","power","powerTime","curtain","message","summary","finalScore","finalDistance","best","start","pause","mute","countdown"].map(id=>[id,document.querySelector(`#${id}`)]));
const scene=new T.Scene();scene.background=new T.Color(0x75c9ef);scene.fog=new T.Fog(0x92d6ef,38,118);
const camera=new T.PerspectiveCamera(58,innerWidth/innerHeight,.1,180),renderer=new T.WebGLRenderer({canvas,antialias:true,powerPreference:"high-performance"});
renderer.setPixelRatio(Math.min(devicePixelRatio,1.35));renderer.setSize(innerWidth,innerHeight);renderer.shadowMap.enabled=true;renderer.shadowMap.type=T.PCFSoftShadowMap;renderer.outputColorSpace=T.SRGBColorSpace;renderer.toneMapping=T.ACESFilmicToneMapping;renderer.toneMappingExposure=1.18;
scene.add(new T.HemisphereLight(0xdff6ff,0x7c5938,2.15));const sun=new T.DirectionalLight(0xfff2cf,3.1);sun.position.set(-18,30,12);sun.castShadow=true;sun.shadow.mapSize.set(1024,1024);sun.shadow.camera.left=-26;sun.shadow.camera.right=26;sun.shadow.camera.top=35;sun.shadow.camera.bottom=-12;scene.add(sun);
const C={red:0xf04f36,blue:0x2479bd,yellow:0xffd447,dark:0x25354b,skin:0xb96f4b,rail:0xd6e0df,wood:0x604735,grass:0x4fa957};
const mat=(c,rough=.7,metal=0)=>new T.MeshStandardMaterial({color:c,roughness:rough,metalness:metal});
const box=(w,h,d,c)=>{const m=new T.Mesh(new T.BoxGeometry(w,h,d),mat(c));m.castShadow=m.receiveShadow=true;return m};
const cyl=(r,h,c)=>{const m=new T.Mesh(new T.CylinderGeometry(r,r,h,12),mat(c));m.castShadow=true;return m};
function add(parent,obj,x=0,y=0,z=0){obj.position.set(x,y,z);parent.add(obj);return obj}
camera.position.set(0,6.3,12.5);camera.lookAt(0,2,-10);
const world=new T.Group();scene.add(world);let actors=[];
function building(x,z,i){const h=7+(i*3%11),g=new T.Group(),palette=[0xe86b50,0x3d83b8,0x785db5,0x45a486,0xf09a4a];add(g,box(5.5,h,5,palette[i%5]),0,h/2,0);for(const xx of [-1.7,-.55,.6,1.75])add(g,box(.42,h*.68,.07,0xd9f4ff),xx,h*.52,2.53);g.position.set(x,0,z);world.add(g)}
function tree(x,z,s=1){const g=new T.Group();add(g,cyl(.16,1.5,0x6b482d),0,.75);const crown=new T.Mesh(new T.IcosahedronGeometry(.85,1),mat(0x3da45d));crown.castShadow=true;add(g,crown,0,1.8);g.scale.setScalar(s);g.position.set(x,0,z);world.add(g)}
for(let i=0;i<14;i++){building((i%2?1:-1)*(12+(i%3)*5),-i*11,i);tree((i%2?1:-1)*(7.5+(i%3)), -i*9, .7+(i%4)*.1)}
const ground=box(42,.25,190,0xc9955a);ground.position.set(0,-.2,-72);ground.receiveShadow=true;world.add(ground);
for(let lane=-1;lane<=1;lane++)for(const side of [-.68,.68]){const r=box(.11,.12,190,C.rail);r.position.set(lane*2.35+side,.08,-72);world.add(r)}
for(let z=15;z>-165;z-=1.7){const tie=box(8.3,.1,.22,C.wood);tie.position.set(0,0,z);world.add(tie)}
function runner(){const g=new T.Group(),rounded=(r,l,c)=>new T.Mesh(new T.CapsuleGeometry(r,l,7,12),mat(c,.55)),torso=add(g,rounded(.5,.75,C.red),0,2.35),head=add(g,new T.Mesh(new T.SphereGeometry(.46,24,18),mat(C.skin,.6)),0,3.55);torso.scale.set(1,.95,.72);const hood=add(g,new T.Mesh(new T.TorusGeometry(.43,.12,10,24,Math.PI*1.25),mat(0xd93f32)),0,3.38,-.24);hood.rotation.z=-.4;const cap=add(g,cyl(.48,.16,C.red),0,3.91);add(g,box(.55,.08,.52,C.red),0,3.86,.32);add(g,rounded(.38,.62,0x2768b1),0,2.45,-.5).rotation.z=Math.PI;add(g,box(.7,.12,.08,0xffefd0),0,2.4,.39);const limbs={};for(const [n,x,y,c,r,l] of [["la",-.67,2.45,C.skin,.13,.83],["ra",.67,2.45,C.skin,.13,.83],["ll",-.25,1.05,C.dark,.16,1.05],["rl",.25,1.05,C.dark,.16,1.05]]){const pivot=new T.Group();pivot.position.set(x,y,0);const mesh=rounded(r,l,c);mesh.position.y=-l*.48;pivot.add(mesh);g.add(pivot);limbs[n]=pivot}for(const x of [-.28,.28]){const shoe=add(g,new T.Mesh(new T.CapsuleGeometry(.2,.4,5,10),mat(C.yellow,.45)),x,.22,.18);shoe.rotation.x=Math.PI/2;shoe.rotation.z=Math.PI/2}g.traverse(o=>{if(o.isMesh)o.castShadow=true});g.scale.setScalar(.92);g.userData={limbs,torso,head};scene.add(g);return g}
const hero=runner();hero.position.set(0,0,2);
function train(lane,z,color){const g=new T.Group();add(g,box(1.85,3.7,5.6,0xf4eee3),0,1.85);add(g,box(1.9,.28,5.65,color),0,2.35);for(const zz of [-2,-.65,.7,2])add(g,box(1.45,.7,.06,0x31546b),0,2.95,zz);add(g,box(1.35,.15,.08,0xffef9c),0,.65,2.84);g.position.set(lane*2.35,0,z);g.userData={type:"train",lane,hit:false};world.add(g);actors.push(g)}
function barrier(lane,z){const g=new T.Group();add(g,box(1.65,1.05,.4,C.red),0,.55);for(const x of [-.55,0,.55]){const s=add(g,box(.18,1.2,.44,C.yellow),x,.55);s.rotation.z=-.55}g.position.set(lane*2.35,0,z);g.userData={type:"barrier",lane,hit:false};world.add(g);actors.push(g)}
function coin(lane,z,y=.9){const m=new T.Mesh(new T.CylinderGeometry(.27,.27,.09,20),mat(C.yellow,.25,.7));m.rotation.z=Math.PI/2;m.position.set(lane*2.35,y,z);m.castShadow=true;m.userData={type:"coin",lane};world.add(m);actors.push(m)}
function powerup(lane,z,type){const g=new T.Group(),colors={magnet:0xf04f5e,board:0x24b8df,jetpack:0xf28c34,boost:0x8658d6};add(g,new T.Mesh(new T.OctahedronGeometry(.42),mat(colors[type],.25,.35)),0,1.1);g.position.set(lane*2.35,0,z);g.userData={type:"power",power:type,lane};world.add(g);actors.push(g)}
let state="menu",speed=18,distance=0,score=0,coins=0,multi=1,lane=0,laneX=0,jumpY=0,vy=0,roll=0,spawn=-28,last=performance.now(),muted=false,power={type:"",time:0},mission={type:"coins",target:25,progress:0},audio;
const store={get(k,d=0){try{return JSON.parse(localStorage.getItem("cityRush."+k))??d}catch{return d}},set(k,v){try{localStorage.setItem("cityRush."+k,JSON.stringify(v))}catch{}}};
function tone(f=440){if(muted)return;audio||=new(window.AudioContext||window.webkitAudioContext)();const o=audio.createOscillator(),g=audio.createGain();o.frequency.value=f;g.gain.setValueAtTime(.06,audio.currentTime);g.gain.exponentialRampToValueAtTime(.001,audio.currentTime+.13);o.connect(g).connect(audio.destination);o.start();o.stop(audio.currentTime+.14)}
function spawnSet(){const open=(Math.random()*3|0)-1,z=spawn;for(const l of [-1,0,1])if(l!==open&&Math.random()<.6)(Math.random()<.45?barrier:train)(l,z-Math.random()*3,[C.red,C.blue,0x42a96c][(Math.random()*3)|0]);for(let i=0;i<7;i++)coin(open,z-i*2.1,.85+Math.sin(i/6*Math.PI)*1.9);if(Math.random()<.38)powerup(open,z-15,["magnet","board","jetpack","boost"][(Math.random()*4)|0]);spawn-=25+Math.random()*12}
function reset(){actors.forEach(a=>world.remove(a));actors.length=0;state="playing";speed=18;distance=score=coins=0;multi=1;lane=laneX=jumpY=vy=roll=0;spawn=-28;power={type:"",time:0};mission={type:"coins",target:25,progress:0};for(let i=0;i<6;i++)spawnSet();ui.curtain.classList.add("hidden");ui.summary.classList.remove("show")}
function jump(){if(state==="playing"&&jumpY<.05){vy=10.8;tone(270)}}function duck(){if(state==="playing"){roll=.7;tone(160)}}function move(d){if(state==="playing")lane=Math.max(-1,Math.min(1,lane+d))}
function die(){if(power.type==="board"){power={type:"",time:0};tone(110);return}state="over";const best=Math.max(store.get("best"),score|0);store.set("best",best);setTimeout(()=>{ui.finalScore.textContent=(score|0).toLocaleString();ui.finalDistance.textContent=`${distance|0}m`;ui.best.textContent=best.toLocaleString();ui.message.textContent="The inspector caught up. Time to make him regret it.";ui.summary.classList.add("show");ui.start.textContent="RUN AGAIN";ui.curtain.classList.remove("hidden")},500)}
function update(dt){if(state!=="playing")return;speed=Math.min(34,18+distance/500);distance+=speed*dt;score+=speed*dt*multi;laneX+=(lane*2.35-laneX)*Math.min(1,dt*12);vy-=27*dt;jumpY+=vy*dt;if(jumpY<0)jumpY=vy=0;roll=Math.max(0,roll-dt);if(power.time>0){power.time-=dt;if(power.time<=0)power={type:"",time:0}}hero.position.x=laneX;hero.position.y=jumpY;hero.scale.y=roll?0.52:1;hero.rotation.z=(lane*2.35-laneX)*-.08;const run=Math.sin(distance*1.1);hero.userData.limbs.la.rotation.x=run*.75;hero.userData.limbs.ra.rotation.x=-run*.75;hero.userData.limbs.ll.rotation.x=-run*.7;hero.userData.limbs.rl.rotation.x=run*.7;if(jumpY>.2){hero.userData.limbs.la.rotation.x=-2.2;hero.userData.limbs.ra.rotation.x=-2.2;hero.userData.limbs.ll.rotation.x=1;hero.userData.limbs.rl.rotation.x=1}camera.position.x+=(laneX*.23-camera.position.x)*dt*3;camera.lookAt(laneX*.12,2,-9);
 for(const a of actors){a.position.z+=speed*dt;if(a.userData.type==="coin")a.rotation.y+=dt*7;if(a.userData.type==="power")a.rotation.y+=dt*3;const dz=Math.abs(a.position.z-2),dx=Math.abs(a.position.x-laneX);if(dz<1&&dx<.8){if(a.userData.type==="coin"){world.remove(a);a.userData.dead=true;coins++;score+=100*multi;mission.progress++;tone(820)}else if(a.userData.type==="power"){power={type:a.userData.power,time:9};world.remove(a);a.userData.dead=true;multi=a.userData.power==="boost"?5:multi;tone(520)}else if(!a.userData.hit){const clear=a.userData.type==="barrier"&&jumpY>1.15;a.userData.hit=true;if(!clear)die();else score+=250}}}actors=actors.filter(a=>!a.userData.dead&&a.position.z<14);while(spawn>-80-distance)spawnSet();ui.score.textContent=(score|0).toLocaleString();ui.coins.textContent=coins;ui.multi.textContent=`×${multi}`;ui.missionBar.style.width=`${Math.min(100,mission.progress/mission.target*100)}%`;ui.power.classList.toggle("show",power.time>0);if(power.time>0){ui.power.querySelector("span").textContent=power.type.toUpperCase();ui.powerTime.textContent=power.time.toFixed(1)}}
function loop(n){const dt=Math.min(.04,(n-last)/1000);last=n;update(dt);renderer.render(scene,camera);requestAnimationFrame(loop)}requestAnimationFrame(loop);
addEventListener("resize",()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight)});
addEventListener("keydown",e=>{if(["ArrowLeft","a"].includes(e.key))move(-1);if(["ArrowRight","d"].includes(e.key))move(1);if(["ArrowUp","w"," "].includes(e.key))jump();if(["ArrowDown","s"].includes(e.key))duck()});
let touch;canvas.addEventListener("pointerdown",e=>touch={x:e.clientX,y:e.clientY});canvas.addEventListener("pointerup",e=>{if(!touch)return;const x=e.clientX-touch.x,y=e.clientY-touch.y;Math.abs(x)>Math.abs(y)?move(x>0?1:-1):y<0?jump():duck();touch=null});
ui.start.onclick=reset;ui.pause.onclick=()=>{state=state==="playing"?"paused":"playing";ui.pause.textContent=state==="paused"?"▶":"Ⅱ"};ui.mute.onclick=()=>{muted=!muted;ui.mute.textContent=muted?"×":"♪"};
