const canvas=document.querySelector('#game'),ctx=canvas.getContext('2d');
const $=s=>document.querySelector(s),scoreEl=$('#score'),highEl=$('#high'),levelEl=$('#level'),livesEl=$('#lives'),overlay=$('#overlay'),titleEl=$('#title'),msgEl=$('#message');
const TILE=20,COLS=28,ROWS=31,W=COLS*TILE,H=ROWS*TILE;
const raw=[
"############################","#............##............#","#.####.#####.##.#####.####.#","#o####.#####.##.#####.####o#","#.####.#####.##.#####.####.#","#..........................#","#.####.##.########.##.####.#","#.####.##.########.##.####.#","#......##....##....##......#","######.##### ## #####.######","     #.##### ## #####.#     ","     #.##          ##.#     ","     #.## ###--### ##.#     ","######.## #      # ##.######","      .   #      #   .      ","######.## #      # ##.######","     #.## ######## ##.#     ","     #.##          ##.#     ","     #.## ######## ##.#     ","######.## ######## ##.######","#............##............#","#.####.#####.##.#####.####.#","#o..##................##..o#","###.##.##.########.##.##.###","#......##....##....##......#","#.##########.##.##########.#","#..........................#","#.####.#####.##.#####.####.#","#.####.#####.##.#####.####.#","#............##............#","############################"];
let map,score=0,high=+(localStorage.halPacHigh||0),level=1,lives=3,state='ready',power=0,combo=0,last=0,fruit=null,fruitTimer=0,audio,fruitsSpawned=0,nextLife=10000,shake=0;
const themes=[
 {name:'NEON NIGHT',wall:'#2864ff',fill:'#071052',dot:'#ffd7a8',bg:'#000'},
 {name:'CYBER MINT',wall:'#00edc3',fill:'#003a3b',dot:'#c8fff1',bg:'#001010'},
 {name:'PURPLE HAZE',wall:'#ba5cff',fill:'#2d0752',dot:'#ffd4ff',bg:'#0e0018'},
 {name:'INFERNO',wall:'#ff5b28',fill:'#551500',dot:'#ffe0a8',bg:'#160500'},
 {name:'ICE GRID',wall:'#7de8ff',fill:'#073952',dot:'#fff',bg:'#001018'}];
highEl.textContent=high;
const dirs={left:{x:-1,y:0,a:Math.PI},right:{x:1,y:0,a:0},up:{x:0,y:-1,a:-Math.PI/2},down:{x:0,y:1,a:Math.PI/2}},opposite={left:'right',right:'left',up:'down',down:'up'};
function resetMap(){map=raw.map(r=>[...r]);}
function cellOpen(x,y){if(y<0||y>=ROWS)return false;if(x<0||x>=COLS)return y===14;return map[y][x]!=='#'&&map[y][x]!=='-';}
function center(e){return Math.abs(((e.x%TILE)+TILE)%TILE-TILE/2)<1.05&&Math.abs(((e.y%TILE)+TILE)%TILE-TILE/2)<1.05}
function snap(e){e.x=Math.floor(e.x/TILE)*TILE+TILE/2;e.y=Math.floor(e.y/TILE)*TILE+TILE/2}
function available(e){let x=Math.floor(e.x/TILE),y=Math.floor(e.y/TILE);return Object.keys(dirs).filter(k=>cellOpen(x+dirs[k].x,y+dirs[k].y));}
function actor(tx,ty,dir,color){return{x:tx*TILE+10,y:ty*TILE+10,dir,next:dir,color,homeX:tx,homeY:ty,dead:0};}
let pac,ghosts;
function resetGhost(g,i){Object.assign(g,actor(9+i,8,i%2?'right':'left',g.color));g.scatter=i;g.release=i*.8;}
function resetActors(){pac=actor(13,26,'left','#ffd928');pac.mouth=0;ghosts=[actor(9,8,'left','#ff3b50'),actor(10,8,'right','#ff82c8'),actor(11,8,'left','#29d8ff'),actor(12,8,'right','#ff9d37')];ghosts.forEach(resetGhost);power=0;combo=0;}
function newGame(){score=0;level=1;lives=3;nextLife=10000;fruitsSpawned=0;resetMap();resetActors();updateHud();startRound();}
function modeText(){if(level%5===0)return 'BONUS BLITZ · DOUBLE DOTS · FAST CREW';if(level%3===0)return 'PANIC MODE · SMARTER GHOSTS';return themes[(level-1)%themes.length].name;}
function startRound(){state='count';titleEl.textContent=level%5===0?'BONUS BLITZ!':'READY!';msgEl.innerHTML=`LEVEL ${level} · ${modeText()}<br><small>${level===1?'Clear the maze. Avoid the crew.':'New colors, faster ghosts, bigger rewards.'}</small>`;$('#start').textContent='GO!';overlay.classList.remove('hidden');}
function begin(){initAudio();if(state==='ready'||state==='gameover')newGame();else if(state==='count'||state==='paused'){state='play';overlay.classList.add('hidden');beep(520,.08,'square');}}
$('#start').onclick=begin;
function updateHud(){scoreEl.textContent=score.toLocaleString();high=Math.max(score,high);highEl.textContent=high.toLocaleString();localStorage.halPacHigh=high;levelEl.textContent=level;livesEl.textContent=lives;}
function addScore(points){score+=points;if(score>=nextLife){lives++;nextLife+=25000;beep(1040,.3,'square',.06);shake=.4;}updateHud();}
function initAudio(){if(!audio)audio=new (window.AudioContext||window.webkitAudioContext)();if(audio.state==='suspended')audio.resume();}
function beep(f,d=.05,type='sine',vol=.04){if(!audio)return;let o=audio.createOscillator(),g=audio.createGain();o.type=type;o.frequency.value=f;g.gain.setValueAtTime(vol,audio.currentTime);g.gain.exponentialRampToValueAtTime(.0001,audio.currentTime+d);o.connect(g).connect(audio.destination);o.start();o.stop(audio.currentTime+d);}
function chooseGhost(g){let opts=available(g).filter(d=>d!==opposite[g.dir]);if(!opts.length)opts=[opposite[g.dir]];if(power>0)return opts[Math.floor(Math.random()*opts.length)];let gx=Math.floor(g.x/TILE),gy=Math.floor(g.y/TILE),px=Math.floor(pac.x/TILE),py=Math.floor(pac.y/TILE),target;
 if(g.color==='#ff3b50')target={x:px,y:py};else if(g.color==='#ff82c8')target={x:px+dirs[pac.dir].x*4,y:py+dirs[pac.dir].y*4};else if(g.color==='#29d8ff')target=Math.hypot(gx-px,gy-py)>7?{x:px,y:py}:{x:1,y:29};else target={x:26,y:29};
 if((performance.now()/1000|0)%18>13)target=[{x:26,y:1},{x:1,y:1},{x:26,y:29},{x:1,y:29}][g.scatter];
 return opts.sort((a,b)=>Math.hypot(gx+dirs[a].x-target.x,gy+dirs[a].y-target.y)-Math.hypot(gx+dirs[b].x-target.x,gy+dirs[b].y-target.y))[0];}
function move(e,speed,dt,isPac=false){let remaining=speed*dt;while(remaining>0){if(center(e)){snap(e);let x=Math.floor(e.x/TILE),y=Math.floor(e.y/TILE);if(isPac&&e.next&&cellOpen(x+dirs[e.next].x,y+dirs[e.next].y))e.dir=e.next;if(!isPac)e.dir=chooseGhost(e);if(!cellOpen(x+dirs[e.dir].x,y+dirs[e.dir].y))return;}let step=Math.min(.8,remaining);e.x+=dirs[e.dir].x*step;e.y+=dirs[e.dir].y*step;remaining-=step;if(e.x<-10)e.x=W+10;if(e.x>W+10)e.x=-10;}}
function update(dt){if(state!=='play')return;power=Math.max(0,power-dt);shake=Math.max(0,shake-dt);fruitTimer=Math.max(0,fruitTimer-dt);if(!fruitTimer)fruit=null;move(pac,105+Math.min(level,12)*3,dt,true);pac.mouth+=dt*12;
 let cx=Math.floor(pac.x/TILE),cy=Math.floor(pac.y/TILE),c=map[cy]?.[cx];if(c==='.'||c==='o'){map[cy][cx]=' ';addScore((c==='o'?50:10)*(level%5===0?2:1));if(c==='o'){power=Math.max(3.5,7-level*.22);combo=0;shake=.18;beep(180,.16,'sawtooth');}else beep(600,.025,'square',.018);let left=map.flat().filter(x=>x==='.'||x==='o').length;if((left===150||left===65)&&fruitsSpawned<(left===150?1:2)){fruit={x:13.5*TILE,y:17.5*TILE,type:(level-1)%5};fruitTimer=10;fruitsSpawned++;}if(!left){state='count';addScore(1000*level);level++;fruitsSpawned=0;resetMap();resetActors();setTimeout(startRound,400);return;}}
 if(fruit&&Math.hypot(pac.x-fruit.x,pac.y-fruit.y)<17){addScore((500+fruit.type*250)*level);fruit=null;fruitTimer=0;shake=.25;beep(880,.2,'triangle');}
 ghosts.forEach((g,i)=>{if(g.release>0){g.release-=dt;return;}let frenzy=level%5===0?12:0;move(g,power>0?70:88+Math.min(level,15)*2+frenzy,dt);if(Math.hypot(pac.x-g.x,pac.y-g.y)<15){if(power>0){addScore(200*(2**combo++));beep(980,.12,'square');resetGhost(g,i);g.release=.7;}else die();}});}
function die(){if(state!=='play')return;state='dying';beep(120,.7,'sawtooth',.06);setTimeout(()=>{lives--;updateHud();if(lives<=0){state='gameover';titleEl.textContent='GAME OVER';msgEl.innerHTML=`SCORE ${score.toLocaleString()}<br><small>The maze remembers. Go again?</small>`;$('#start').textContent='PLAY AGAIN';overlay.classList.remove('hidden');}else{resetActors();startRound();}},750);}
function wall(x,y){let px=x*TILE,py=y*TILE,t=themes[(level-1)%themes.length];ctx.fillStyle=t.fill;ctx.fillRect(px,py,TILE,TILE);ctx.strokeStyle=t.wall;ctx.lineWidth=2;ctx.strokeRect(px+2,py+2,TILE-4,TILE-4);}
function drawPac(){let a=dirs[pac.dir].a,m=.18+Math.abs(Math.sin(pac.mouth))*.32;ctx.fillStyle='#ffd928';ctx.beginPath();ctx.moveTo(pac.x,pac.y);ctx.arc(pac.x,pac.y,8.5,a+m,a+Math.PI*2-m);ctx.closePath();ctx.fill();}
function drawGhost(g){let fright=power>0,flash=power<2&&Math.floor(power*5)%2===0;ctx.fillStyle=fright?(flash?'#fff':'#243cff'):g.color;ctx.beginPath();ctx.arc(g.x,g.y-2,8,Math.PI,0);ctx.lineTo(g.x+8,g.y+8);for(let n=0;n<4;n++)ctx.lineTo(g.x+6-n*4,g.y+5+(n%2)*3);ctx.lineTo(g.x-8,g.y+8);ctx.closePath();ctx.fill();if(!fright){ctx.fillStyle='#fff';ctx.beginPath();ctx.arc(g.x-3,g.y-2,2.6,0,7);ctx.arc(g.x+3,g.y-2,2.6,0,7);ctx.fill();ctx.fillStyle='#1d43a5';ctx.fillRect(g.x-4+dirs[g.dir].x*1.5,g.y-3+dirs[g.dir].y*1.5,2,3);ctx.fillRect(g.x+2+dirs[g.dir].x*1.5,g.y-3+dirs[g.dir].y*1.5,2,3);}}
function draw(){let t=themes[(level-1)%themes.length];ctx.save();if(shake)ctx.translate((Math.random()-.5)*8,(Math.random()-.5)*8);ctx.fillStyle=t.bg;ctx.fillRect(-10,-10,W+20,H+20);for(let y=0;y<ROWS;y++)for(let x=0;x<COLS;x++){let c=map[y][x];if(c==='#')wall(x,y);else if(c==='.'||c==='o'){ctx.fillStyle=c==='o'?'#fff4c7':t.dot;ctx.beginPath();ctx.arc(x*TILE+10,y*TILE+10,c==='o'?4+Math.sin(performance.now()/100)*.8:1.6,0,7);ctx.fill();}}if(fruit){let colors=['#ff2c4b','#ff9d00','#76e34d','#bb5cff','#35e5ff'];ctx.fillStyle=colors[fruit.type];ctx.beginPath();ctx.arc(fruit.x-3,fruit.y,6,0,7);ctx.arc(fruit.x+3,fruit.y,6,0,7);ctx.fill();ctx.strokeStyle='#47c85b';ctx.beginPath();ctx.moveTo(fruit.x,fruit.y-4);ctx.quadraticCurveTo(fruit.x+4,fruit.y-12,fruit.x+9,fruit.y-8);ctx.stroke();}drawPac();ghosts.forEach(drawGhost);if(level%5===0){ctx.strokeStyle='#ffd92855';ctx.lineWidth=2;ctx.strokeRect(4,4,W-8,H-8)}if(state==='paused'){ctx.fillStyle='#fff';ctx.font='bold 22px system-ui';ctx.textAlign='center';ctx.fillText('PAUSED',W/2,H/2);}ctx.restore();}
function loop(t){let dt=Math.min(.035,(t-last)/1000||0);last=t;update(dt);draw();requestAnimationFrame(loop)}requestAnimationFrame(loop);
function setDir(d){initAudio();if(state==='count')begin();if(pac)pac.next=d;}
addEventListener('keydown',e=>{let k={ArrowLeft:'left',a:'left',A:'left',ArrowRight:'right',d:'right',D:'right',ArrowUp:'up',w:'up',W:'up',ArrowDown:'down',s:'down',S:'down'}[e.key];if(k){e.preventDefault();setDir(k)}if(e.key.toLowerCase()==='p'&&['play','paused'].includes(state)){state=state==='play'?'paused':'play';}});
document.querySelectorAll('[data-dir]').forEach(b=>{b.addEventListener('pointerdown',e=>{e.preventDefault();setDir(b.dataset.dir)})});let touch=null;canvas.addEventListener('pointerdown',e=>touch={x:e.clientX,y:e.clientY});canvas.addEventListener('pointerup',e=>{if(!touch)return;let x=e.clientX-touch.x,y=e.clientY-touch.y;if(Math.hypot(x,y)>15)setDir(Math.abs(x)>Math.abs(y)?(x>0?'right':'left'):(y>0?'down':'up'));touch=null});
resetMap();resetActors();draw();
