const canvas=document.querySelector('#game'),ctx=canvas.getContext('2d');
const $=s=>document.querySelector(s),scoreEl=$('#score'),highEl=$('#high'),levelEl=$('#level'),livesEl=$('#lives'),overlay=$('#overlay'),titleEl=$('#title'),msgEl=$('#message');
const TILE=20,COLS=28,ROWS=31,W=COLS*TILE,H=ROWS*TILE;
const raw=[
"############################","#............##............#","#.####.#####.##.#####.####.#","#o####.#####.##.#####.####o#","#.####.#####.##.#####.####.#","#..........................#","#.####.##.########.##.####.#","#.####.##.########.##.####.#","#......##....##....##......#","######.##### ## #####.######","     #.##### ## #####.#     ","     #.##          ##.#     ","     #.## ###--### ##.#     ","######.## #      # ##.######","      .   #      #   .      ","######.## #      # ##.######","     #.## ######## ##.#     ","     #.##          ##.#     ","     #.## ######## ##.#     ","######.## ######## ##.######","#............##............#","#.####.#####.##.#####.####.#","#o..##................##..o#","###.##.##.########.##.##.###","#......##....##....##......#","#.##########.##.##########.#","#..........................#","#.####.#####.##.#####.####.#","#.####.#####.##.#####.####.#","#............##............#","############################"];
let map,score=0,high=+(localStorage.halPacHigh||0),level=1,lives=3,state='ready',power=0,combo=0,last=0,fruit=null,fruitTimer=0,audio;
highEl.textContent=high;
const dirs={left:{x:-1,y:0,a:Math.PI},right:{x:1,y:0,a:0},up:{x:0,y:-1,a:-Math.PI/2},down:{x:0,y:1,a:Math.PI/2}},opposite={left:'right',right:'left',up:'down',down:'up'};
function resetMap(){map=raw.map(r=>[...r]);}
function cellOpen(x,y){if(y<0||y>=ROWS)return false;if(x<0||x>=COLS)return y===14;return map[y][x]!=='#'&&map[y][x]!=='-';}
function center(e){return Math.abs(e.x%TILE-TILE/2)<1.8&&Math.abs(e.y%TILE-TILE/2)<1.8}
function snap(e){e.x=Math.floor(e.x/TILE)*TILE+TILE/2;e.y=Math.floor(e.y/TILE)*TILE+TILE/2}
function available(e){let x=Math.floor(e.x/TILE),y=Math.floor(e.y/TILE);return Object.keys(dirs).filter(k=>cellOpen(x+dirs[k].x,y+dirs[k].y));}
function actor(tx,ty,dir,color){return{x:tx*TILE+10,y:ty*TILE+10,dir,next:dir,color,homeX:tx,homeY:ty,dead:0};}
let pac,ghosts;
function resetActors(){pac=actor(13,23,'left','#ffd928');pac.mouth=0;ghosts=[actor(13,11,'left','#ff3b50'),actor(14,14,'up','#ff82c8'),actor(12,14,'left','#29d8ff'),actor(15,14,'right','#ff9d37')];ghosts.forEach((g,i)=>{g.scatter=i;g.release=i*1.7;});power=0;combo=0;}
function newGame(){score=0;level=1;lives=3;resetMap();resetActors();updateHud();startRound();}
function startRound(){state='count';titleEl.textContent='READY!';msgEl.innerHTML=`LEVEL ${level}<br><small>Clear the maze. Avoid the crew.</small>`;$('#start').textContent='GO!';overlay.classList.remove('hidden');}
function begin(){initAudio();if(state==='ready'||state==='gameover')newGame();else if(state==='count'||state==='paused'){state='play';overlay.classList.add('hidden');beep(520,.08,'square');}}
$('#start').onclick=begin;
function updateHud(){scoreEl.textContent=score.toLocaleString();high=Math.max(score,high);highEl.textContent=high.toLocaleString();localStorage.halPacHigh=high;levelEl.textContent=level;livesEl.textContent=lives;}
function initAudio(){if(!audio)audio=new (window.AudioContext||window.webkitAudioContext)();if(audio.state==='suspended')audio.resume();}
function beep(f,d=.05,type='sine',vol=.04){if(!audio)return;let o=audio.createOscillator(),g=audio.createGain();o.type=type;o.frequency.value=f;g.gain.setValueAtTime(vol,audio.currentTime);g.gain.exponentialRampToValueAtTime(.0001,audio.currentTime+d);o.connect(g).connect(audio.destination);o.start();o.stop(audio.currentTime+d);}
function chooseGhost(g){let opts=available(g).filter(d=>d!==opposite[g.dir]);if(!opts.length)opts=[opposite[g.dir]];if(power>0)return opts[Math.floor(Math.random()*opts.length)];let gx=Math.floor(g.x/TILE),gy=Math.floor(g.y/TILE),px=Math.floor(pac.x/TILE),py=Math.floor(pac.y/TILE),target;
 if(g.color==='#ff3b50')target={x:px,y:py};else if(g.color==='#ff82c8')target={x:px+dirs[pac.dir].x*4,y:py+dirs[pac.dir].y*4};else if(g.color==='#29d8ff')target=Math.hypot(gx-px,gy-py)>7?{x:px,y:py}:{x:1,y:29};else target={x:26,y:29};
 if((performance.now()/1000|0)%18>13)target=[{x:26,y:1},{x:1,y:1},{x:26,y:29},{x:1,y:29}][g.scatter];
 return opts.sort((a,b)=>Math.hypot(gx+dirs[a].x-target.x,gy+dirs[a].y-target.y)-Math.hypot(gx+dirs[b].x-target.x,gy+dirs[b].y-target.y))[0];}
function move(e,speed,dt,isPac=false){if(center(e)){snap(e);let x=Math.floor(e.x/TILE),y=Math.floor(e.y/TILE);if(isPac&&e.next&&cellOpen(x+dirs[e.next].x,y+dirs[e.next].y))e.dir=e.next;if(!isPac)e.dir=chooseGhost(e);if(!cellOpen(x+dirs[e.dir].x,y+dirs[e.dir].y))return;}e.x+=dirs[e.dir].x*speed*dt;e.y+=dirs[e.dir].y*speed*dt;if(e.x<-10)e.x=W+10;if(e.x>W+10)e.x=-10;}
function update(dt){if(state!=='play')return;power=Math.max(0,power-dt);fruitTimer=Math.max(0,fruitTimer-dt);if(!fruitTimer)fruit=null;move(pac,105+level*3,dt,true);pac.mouth+=dt*12;
 let cx=Math.floor(pac.x/TILE),cy=Math.floor(pac.y/TILE),c=map[cy]?.[cx];if(c==='.'||c==='o'){map[cy][cx]=' ';score+=c==='o'?50:10;if(c==='o'){power=7;combo=0;beep(180,.16,'sawtooth');}else beep(600,.025,'square',.018);updateHud();let left=map.flat().filter(x=>x==='.'||x==='o').length;if(left===100&&!fruit){fruit={x:13.5*TILE,y:17.5*TILE};fruitTimer=10;}if(!left){state='count';score+=1000;level++;resetMap();resetActors();updateHud();setTimeout(startRound,400);return;}}
 if(fruit&&Math.hypot(pac.x-fruit.x,pac.y-fruit.y)<17){score+=500*level;fruit=null;fruitTimer=0;beep(880,.2,'triangle');updateHud();}
 ghosts.forEach((g,i)=>{if(g.release>0){g.release-=dt;return;}move(g,power>0?70:88+level*2,dt);if(Math.hypot(pac.x-g.x,pac.y-g.y)<15){if(power>0){score+=200*(2**combo++);beep(980,.12,'square');Object.assign(g,actor(13+(i%2),14,i%2?'right':'left',g.color));g.release=1;updateHud();}else die();}});}
function die(){if(state!=='play')return;state='dying';beep(120,.7,'sawtooth',.06);setTimeout(()=>{lives--;updateHud();if(lives<=0){state='gameover';titleEl.textContent='GAME OVER';msgEl.innerHTML=`SCORE ${score.toLocaleString()}<br><small>The maze remembers. Go again?</small>`;$('#start').textContent='PLAY AGAIN';overlay.classList.remove('hidden');}else{resetActors();startRound();}},750);}
function wall(x,y){let px=x*TILE,py=y*TILE;ctx.fillStyle='#071052';ctx.fillRect(px,py,TILE,TILE);ctx.strokeStyle='#2864ff';ctx.lineWidth=2;ctx.strokeRect(px+2,py+2,TILE-4,TILE-4);}
function drawPac(){let a=dirs[pac.dir].a,m=.18+Math.abs(Math.sin(pac.mouth))*.32;ctx.fillStyle='#ffd928';ctx.beginPath();ctx.moveTo(pac.x,pac.y);ctx.arc(pac.x,pac.y,8.5,a+m,a+Math.PI*2-m);ctx.closePath();ctx.fill();}
function drawGhost(g){let fright=power>0,flash=power<2&&Math.floor(power*5)%2===0;ctx.fillStyle=fright?(flash?'#fff':'#243cff'):g.color;ctx.beginPath();ctx.arc(g.x,g.y-2,8,Math.PI,0);ctx.lineTo(g.x+8,g.y+8);for(let n=0;n<4;n++)ctx.lineTo(g.x+6-n*4,g.y+5+(n%2)*3);ctx.lineTo(g.x-8,g.y+8);ctx.closePath();ctx.fill();if(!fright){ctx.fillStyle='#fff';ctx.beginPath();ctx.arc(g.x-3,g.y-2,2.6,0,7);ctx.arc(g.x+3,g.y-2,2.6,0,7);ctx.fill();ctx.fillStyle='#1d43a5';ctx.fillRect(g.x-4+dirs[g.dir].x*1.5,g.y-3+dirs[g.dir].y*1.5,2,3);ctx.fillRect(g.x+2+dirs[g.dir].x*1.5,g.y-3+dirs[g.dir].y*1.5,2,3);}}
function draw(){ctx.fillStyle='#000';ctx.fillRect(0,0,W,H);for(let y=0;y<ROWS;y++)for(let x=0;x<COLS;x++){let c=map[y][x];if(c==='#')wall(x,y);else if(c==='.'||c==='o'){ctx.fillStyle=c==='o'?'#fff4c7':'#ffd7a8';ctx.beginPath();ctx.arc(x*TILE+10,y*TILE+10,c==='o'?4:1.6,0,7);ctx.fill();}}if(fruit){ctx.fillStyle='#ff2c4b';ctx.beginPath();ctx.arc(fruit.x-3,fruit.y,6,0,7);ctx.arc(fruit.x+3,fruit.y,6,0,7);ctx.fill();ctx.strokeStyle='#47c85b';ctx.beginPath();ctx.moveTo(fruit.x,fruit.y-4);ctx.quadraticCurveTo(fruit.x+4,fruit.y-12,fruit.x+9,fruit.y-8);ctx.stroke();}drawPac();ghosts.forEach(drawGhost);if(state==='paused'){ctx.fillStyle='#fff';ctx.font='bold 22px system-ui';ctx.textAlign='center';ctx.fillText('PAUSED',W/2,H/2);}}
function loop(t){let dt=Math.min(.035,(t-last)/1000||0);last=t;update(dt);draw();requestAnimationFrame(loop)}requestAnimationFrame(loop);
function setDir(d){initAudio();if(state==='count')begin();if(pac)pac.next=d;}
addEventListener('keydown',e=>{let k={ArrowLeft:'left',a:'left',A:'left',ArrowRight:'right',d:'right',D:'right',ArrowUp:'up',w:'up',W:'up',ArrowDown:'down',s:'down',S:'down'}[e.key];if(k){e.preventDefault();setDir(k)}if(e.key.toLowerCase()==='p'&&['play','paused'].includes(state)){state=state==='play'?'paused':'play';}});
document.querySelectorAll('[data-dir]').forEach(b=>{b.addEventListener('pointerdown',e=>{e.preventDefault();setDir(b.dataset.dir)})});let touch=null;canvas.addEventListener('pointerdown',e=>touch={x:e.clientX,y:e.clientY});canvas.addEventListener('pointerup',e=>{if(!touch)return;let x=e.clientX-touch.x,y=e.clientY-touch.y;if(Math.hypot(x,y)>15)setDir(Math.abs(x)>Math.abs(y)?(x>0?'right':'left'):(y>0?'down':'up'));touch=null});
resetMap();resetActors();draw();
