(()=>{"use strict";
const canvas=document.querySelector("#game"),ctx=canvas.getContext("2d"),panel=document.querySelector("#panel"),start=document.querySelector("#start"),scoreEl=document.querySelector("#score"),bestEl=document.querySelector("#best"),comboEl=document.querySelector("#combo"),lengthEl=document.querySelector("#length"),boostEl=document.querySelector("#boost");
let W=0,H=0,dpr=1,cols=28,rows=20,cell=24,ox=0,oy=0,state="title",last=0,acc=0,clock=0,shake=0,flash=0,boosting=false,energy=100,score=0,best=+(localStorage.neonSerpentBest||0),combo=1,comboLife=0,level=1,foodsEaten=0,dir={x:1,y:0},queued={x:1,y:0},snake=[],food=null,power=null,portals=[],rocks=[],particles=[],floaters=[],stars=[],effect=null,effectLife=0,stepMs=112,touch=null;
bestEl.textContent=best;
const rand=(a,b)=>a+Math.random()*(b-a),pick=a=>a[Math.floor(Math.random()*a.length)],key=(x,y)=>x+","+y;
function resize(){dpr=Math.min(2,devicePixelRatio||1);W=innerWidth;H=innerHeight;canvas.width=W*dpr;canvas.height=H*dpr;ctx.setTransform(dpr,0,0,dpr,0,0);cell=Math.max(15,Math.min(31,Math.floor(Math.min((W-28)/cols,(H-72)/rows))));ox=Math.floor((W-cols*cell)/2);oy=Math.floor((H-rows*cell)/2+20);stars=Array.from({length:90},()=>({x:Math.random()*W,y:Math.random()*H,s:rand(.4,2),a:rand(.15,.7)}));}addEventListener("resize",resize);resize();
function freeSpot(){const used=new Set(snake.map(p=>key(p.x,p.y)));rocks.forEach(p=>used.add(key(p.x,p.y)));portals.forEach(p=>used.add(key(p.x,p.y)));for(let i=0;i<500;i++){const p={x:Math.floor(rand(1,cols-1)),y:Math.floor(rand(1,rows-1))};if(!used.has(key(p.x,p.y)))return p;}return{x:2,y:2};}
function spawnFood(){food={...freeSpot(),kind:Math.random()<.12?"gold":"core",pulse:0};}
function spawnPower(){if(power||Math.random()>.28)return;power={...freeSpot(),kind:pick(["ghost","magnet","slow","shrink"]),life:11000};}
function makePortals(){portals=[{...freeSpot(),h:190},{...freeSpot(),h:315}];}
function reset(){score=0;combo=1;comboLife=0;level=1;foodsEaten=0;energy=100;effect=null;effectLife=0;rocks=[];portals=[];particles=[];floaters=[];dir={x:1,y:0};queued={...dir};snake=[{x:8,y:10},{x:7,y:10},{x:6,y:10},{x:5,y:10}];spawnFood();state="play";panel.style.display="none";last=performance.now();acc=0;updateHud();}
function updateHud(){scoreEl.textContent=score;bestEl.textContent=Math.max(best,score);comboEl.textContent=`COMBO x${combo}`;lengthEl.textContent=snake.length;boostEl.style.width=energy+"%";}
function steer(x,y){if(state!=="play")return;if(x!==-dir.x||y!==-dir.y)queued={x,y};}
function burst(x,y,color,n=18){const px=ox+(x+.5)*cell,py=oy+(y+.5)*cell;for(let i=0;i<n;i++)particles.push({x:px,y:py,vx:rand(-150,150),vy:rand(-150,150),life:rand(.35,.9),color,size:rand(2,6)});}
function say(text,x,y,color="#fff"){floaters.push({text,x:ox+(x+.5)*cell,y:oy+(y+.5)*cell,life:1,color});}
function addRock(){if(rocks.length<Math.min(18,level*2))rocks.push(freeSpot());}
function surprise(){const roll=Math.random();if(roll<.33){effect="disco";effectLife=7000;say("DISCO GARDEN",food.x,food.y,"#ff69e8");}else if(roll<.66){for(let i=0;i<3;i++)addRock();say("GRID SHIFT",food.x,food.y,"#ff8c62");shake=10;}else{effect="feast";effectLife=8000;say("FEAST MODE",food.x,food.y,"#ffe36e");}}
function collectPower(p){effect=p.kind;effectLife=p.kind==="slow"?9000:7000;const names={ghost:"PHASE SHIFT",magnet:"MAGNET MOUTH",slow:"TIME DILATION",shrink:"TAIL PURGE"};if(p.kind==="shrink")snake.splice(Math.max(4,snake.length-4));say(names[p.kind],p.x,p.y,"#82f7ff");burst(p.x,p.y,"#82f7ff",28);power=null;score+=150;}
function step(){dir=queued;const head={x:snake[0].x+dir.x,y:snake[0].y+dir.y};if(effect==="ghost"){head.x=(head.x+cols)%cols;head.y=(head.y+rows)%rows;}if(portals.length){const hit=portals.findIndex(p=>p.x===head.x&&p.y===head.y);if(hit>=0){const out=portals[1-hit];head.x=out.x+dir.x;head.y=out.y+dir.y;burst(out.x,out.y,`hsl(${out.h} 100% 65%)`,24);}}
const self=snake.some((p,i)=>i>1&&p.x===head.x&&p.y===head.y),wall=head.x<0||head.x>=cols||head.y<0||head.y>=rows,rock=rocks.some(p=>p.x===head.x&&p.y===head.y);if((wall||self||rock)&&effect!=="ghost")return die();snake.unshift(head);
let ate=food&&head.x===food.x&&head.y===food.y;if(effect==="magnet"&&food&&Math.abs(head.x-food.x)+Math.abs(head.y-food.y)<=2)ate=true;if(ate){const gold=food.kind==="gold",points=(gold?250:60)*combo;score+=points;foodsEaten++;combo=comboLife>0?Math.min(9,combo+1):1;comboLife=4200;energy=Math.min(100,energy+(gold?45:18));burst(food.x,food.y,gold?"#ffe260":"#67ffc2",gold?35:20);say(`+${points}`,food.x,food.y,gold?"#ffe260":"#67ffc2");if(foodsEaten%5===0){level++;stepMs=Math.max(58,112-level*5);addRock();if(level===3)makePortals();}if(foodsEaten%9===0)surprise();spawnFood();spawnPower();}else snake.pop();if(power&&head.x===power.x&&head.y===power.y)collectPower(power);updateHud();}
function die(){state="dead";boosting=false;shake=22;flash=1;burst(snake[0].x,snake[0].y,"#ff4168",60);if(score>best){best=score;localStorage.neonSerpentBest=best;}setTimeout(()=>{panel.style.display="grid";panel.querySelector("h1").innerHTML="SIGNAL<span>LOST</span>";panel.querySelector(".card p").textContent=`Score ${score}. Length ${snake.length}. The garden remembers every mistake.`;start.textContent="REINCARNATE";},550);}
function update(dt){clock+=dt;if(state!=="play")return;comboLife-=dt;if(comboLife<=0)combo=1;if(effectLife>0){effectLife-=dt;if(effectLife<=0)effect=null;}if(power){power.life-=dt;if(power.life<=0)power=null;}boosting=boosting&&energy>0;if(boosting)energy=Math.max(0,energy-dt*.035);else energy=Math.min(100,energy+dt*.009);const speed=(effect==="slow"?1.35:1)*(boosting?.52:1);acc+=dt;while(acc>stepMs*speed){step();acc-=stepMs*speed;if(state!=="play")break;}particles.forEach(p=>{p.x+=p.vx*dt/1000;p.y+=p.vy*dt/1000;p.vx*=.97;p.vy*=.97;p.life-=dt/1000});particles=particles.filter(p=>p.life>0);floaters.forEach(f=>{f.y-=dt*.035;f.life-=dt/1000});floaters=floaters.filter(f=>f.life>0);shake=Math.max(0,shake-dt*.025);flash=Math.max(0,flash-dt*.003);updateHud();}
function rr(x,y,w,h,r){ctx.beginPath();ctx.roundRect(x,y,w,h,r);ctx.fill();}
function draw(){ctx.save();if(shake)ctx.translate(rand(-shake,shake),rand(-shake,shake));const hue=effect==="disco"?(clock*.08)%360:158;const g=ctx.createRadialGradient(W*.5,H*.45,20,W*.5,H*.45,Math.max(W,H)*.7);g.addColorStop(0,`hsla(${hue},55%,12%,1)`);g.addColorStop(1,"#010307");ctx.fillStyle=g;ctx.fillRect(-30,-30,W+60,H+60);for(const s of stars){ctx.fillStyle=`rgba(150,255,220,${s.a*(.6+.4*Math.sin(clock*.002+s.x))})`;ctx.fillRect(s.x,s.y,s.s,s.s)}
ctx.strokeStyle=`hsla(${hue},80%,60%,.09)`;ctx.lineWidth=1;for(let x=0;x<=cols;x++){ctx.beginPath();ctx.moveTo(ox+x*cell,oy);ctx.lineTo(ox+x*cell,oy+rows*cell);ctx.stroke()}for(let y=0;y<=rows;y++){ctx.beginPath();ctx.moveTo(ox,oy+y*cell);ctx.lineTo(ox+cols*cell,oy+y*cell);ctx.stroke()}ctx.strokeStyle=`hsla(${hue},90%,65%,.32)`;ctx.strokeRect(ox,oy,cols*cell,rows*cell);
rocks.forEach((p,i)=>{const x=ox+p.x*cell,y=oy+p.y*cell;ctx.fillStyle="#321a38";ctx.shadowColor="#ff4a8d";ctx.shadowBlur=8;ctx.beginPath();ctx.moveTo(x+3,y+cell-3);ctx.lineTo(x+cell*.3,y+5);ctx.lineTo(x+cell-4,y+cell*.35);ctx.lineTo(x+cell-3,y+cell-3);ctx.fill();ctx.shadowBlur=0});
portals.forEach((p,i)=>{const x=ox+(p.x+.5)*cell,y=oy+(p.y+.5)*cell;ctx.strokeStyle=`hsl(${p.h} 100% 65%)`;ctx.lineWidth=3;ctx.shadowColor=ctx.strokeStyle;ctx.shadowBlur=15;ctx.beginPath();ctx.arc(x,y,cell*.42,clock*.004+(i?Math.PI:0),clock*.004+Math.PI*1.55+(i?Math.PI:0));ctx.stroke();ctx.shadowBlur=0});
if(food){food.pulse+=.08;const x=ox+(food.x+.5)*cell,y=oy+(food.y+.5)*cell,r=cell*(food.kind==="gold"?.36:.29)*(1+Math.sin(clock*.008)*.1);ctx.fillStyle=food.kind==="gold"?"#ffe268":"#61ffc0";ctx.shadowColor=ctx.fillStyle;ctx.shadowBlur=22;ctx.beginPath();ctx.arc(x,y,r,0,7);ctx.fill();ctx.fillStyle="#fff";ctx.beginPath();ctx.arc(x-r*.25,y-r*.3,r*.23,0,7);ctx.fill();ctx.shadowBlur=0;}
if(power){const x=ox+(power.x+.5)*cell,y=oy+(power.y+.5)*cell;ctx.save();ctx.translate(x,y);ctx.rotate(clock*.002);ctx.fillStyle="#7aeaff";ctx.shadowColor="#7aeaff";ctx.shadowBlur=18;ctx.fillRect(-cell*.25,-cell*.25,cell*.5,cell*.5);ctx.fillStyle="#08232b";ctx.font=`900 ${cell*.45}px monospace`;ctx.textAlign="center";ctx.textBaseline="middle";ctx.fillText({ghost:"G",magnet:"M",slow:"T",shrink:"S"}[power.kind],0,1);ctx.restore();}
for(let i=snake.length-1;i>=0;i--){const p=snake[i],x=ox+p.x*cell+2,y=oy+p.y*cell+2,t=1-i/Math.max(1,snake.length),isHead=i===0;ctx.fillStyle=`hsl(${150+t*25} 90% ${isHead?66:38+t*20}%)`;ctx.shadowColor="#42ffc0";ctx.shadowBlur=isHead?18:6;rr(x,y,cell-4,cell-4,isHead?cell*.38:cell*.25);if(isHead){ctx.shadowBlur=0;ctx.fillStyle="#07130f";const side=dir.x?0:dir.y;const ex1=x+cell*(dir.x>0?.69:dir.x<0?.22:.3),ex2=x+cell*(dir.x>0?.69:dir.x<0?.22:.61),ey1=y+cell*(dir.y>0?.69:dir.y<0?.22:.3),ey2=y+cell*(dir.y>0?.69:dir.y<0?.22:.61);ctx.beginPath();ctx.arc(ex1,ey1,2.1,0,7);ctx.arc(ex2,ey2,2.1,0,7);ctx.fill();}}
ctx.shadowBlur=0;particles.forEach(p=>{ctx.globalAlpha=Math.max(0,p.life);ctx.fillStyle=p.color;ctx.fillRect(p.x,p.y,p.size,p.size)});ctx.globalAlpha=1;floaters.forEach(f=>{ctx.globalAlpha=f.life;ctx.fillStyle=f.color;ctx.font="900 16px ui-monospace";ctx.textAlign="center";ctx.fillText(f.text,f.x,f.y)});ctx.globalAlpha=1;if(effect){ctx.fillStyle="#ffffff88";ctx.font="800 10px ui-monospace";ctx.textAlign="left";ctx.fillText(effect.toUpperCase()+" ACTIVE",ox+8,oy+18)}if(flash){ctx.fillStyle=`rgba(255,60,100,${flash*.35})`;ctx.fillRect(0,0,W,H)}ctx.restore();}
function loop(t){const dt=Math.min(40,t-last||16);last=t;update(dt);draw();requestAnimationFrame(loop)}requestAnimationFrame(loop);
addEventListener("keydown",e=>{const k=e.key.toLowerCase(),m={arrowup:[0,-1],w:[0,-1],arrowdown:[0,1],s:[0,1],arrowleft:[-1,0],a:[-1,0],arrowright:[1,0],d:[1,0]};if(m[k]){e.preventDefault();steer(...m[k])}if(k===" "){e.preventDefault();boosting=true}if(k==="p"&&state!=="title"){state=state==="pause"?"play":"pause";panel.style.display=state==="pause"?"grid":"none";if(state==="pause"){panel.querySelector("h1").innerHTML="SYSTEM<span>PAUSED</span>";panel.querySelector(".card p").textContent="The serpent is holding very, very still.";start.textContent="RESUME";}}});addEventListener("keyup",e=>{if(e.key===" ")boosting=false});
canvas.addEventListener("pointerdown",e=>touch={x:e.clientX,y:e.clientY});canvas.addEventListener("pointerup",e=>{if(!touch)return;const dx=e.clientX-touch.x,dy=e.clientY-touch.y;if(Math.hypot(dx,dy)>25)Math.abs(dx)>Math.abs(dy)?steer(Math.sign(dx),0):steer(0,Math.sign(dy));touch=null});document.querySelectorAll("[data-dir]").forEach(b=>b.onpointerdown=e=>{e.preventDefault();const m={up:[0,-1],down:[0,1],left:[-1,0],right:[1,0]}[b.dataset.dir];steer(...m)});const dash=document.querySelector("#dash");dash.onpointerdown=e=>{e.preventDefault();boosting=true};dash.onpointerup=dash.onpointercancel=()=>boosting=false;start.onclick=()=>state==="pause"?(state="play",panel.style.display="none"):reset();
})();
