const canvas=document.querySelector('#game'),ctx=canvas.getContext('2d'),stage=document.querySelector('#stage'),overlay=document.querySelector('#overlay'),scoreEl=document.querySelector('#score'),waveEl=document.querySelector('#wave'),bestEl=document.querySelector('#best'),flash=document.querySelector('#flash');
let W,H,cx,cy,scale,dpr,ship,objects=[],particles=[],stars=[],score=0,best=+(localStorage.orbitBest||0),wave=1,state='ready',last=0,spawn=0,coreSpawn=0,combo=0,shield=0,slow=0,audio,elapsed=0;
bestEl.textContent=best;
function resize(){let r=stage.getBoundingClientRect();dpr=Math.min(devicePixelRatio||1,2);W=r.width;H=r.height;canvas.width=W*dpr;canvas.height=H*dpr;ctx.setTransform(dpr,0,0,dpr,0,0);cx=W/2;cy=H*.52;scale=Math.min(W,H)/430;stars=Array.from({length:70},()=>({x:Math.random()*W,y:Math.random()*H,s:Math.random()*1.8+.3,a:Math.random()}));if(ship)ship.r=Math.min(W,H)*.245;}
addEventListener('resize',resize);resize();
function initAudio(){if(!audio)audio=new (window.AudioContext||window.webkitAudioContext)();if(audio.state==='suspended')audio.resume()}
function beep(f,d=.06,type='sine',v=.04){if(!audio)return;let o=audio.createOscillator(),g=audio.createGain();o.type=type;o.frequency.value=f;g.gain.setValueAtTime(v,audio.currentTime);g.gain.exponentialRampToValueAtTime(.0001,audio.currentTime+d);o.connect(g).connect(audio.destination);o.start();o.stop(audio.currentTime+d)}
function reset(){score=0;wave=1;objects=[];particles=[];combo=0;shield=0;slow=0;elapsed=0;spawn=.8;coreSpawn=2;ship={a:-Math.PI/2,dir:1,r:Math.min(W,H)*.245,speed:1.65};updateHud()}
function updateHud(){scoreEl.textContent=Math.floor(score).toLocaleString();waveEl.textContent=wave;best=Math.max(best,Math.floor(score));bestEl.textContent=best.toLocaleString();localStorage.orbitBest=best}
function start(){initAudio();reset();state='play';overlay.classList.add('hidden');beep(440,.12,'triangle')}
document.querySelector('#start').onclick=start;
function reverse(){initAudio();if(state==='ready'||state==='dead'){start();return}if(state!=='play')return;ship.dir*=-1;ship.speed=Math.min(ship.speed+.025,3);burst(shipPos().x,shipPos().y,'#fff',8);beep(ship.dir>0?630:520,.045,'square',.025)}
stage.addEventListener('pointerdown',e=>{e.preventDefault();reverse()});addEventListener('keydown',e=>{if([' ','ArrowLeft','ArrowRight'].includes(e.key)){e.preventDefault();reverse()}});
function shipPos(){return{x:cx+Math.cos(ship.a)*ship.r,y:cy+Math.sin(ship.a)*ship.r}}
function addObject(type){let side=Math.random()<.5?-1:1,a=Math.random()*Math.PI*2,r=ship.r+(type==='meteor'?(65+Math.random()*80)*side:0);if(type==='core')r=ship.r;objects.push({type,a,r,size:type==='meteor'?10+Math.random()*8:8,speed:type==='meteor'?(Math.random()*.35+.18)*-side:0,spin:Math.random()*6.28,kind:type==='power'?Math.random()<.5?'shield':'slow':null})}
function burst(x,y,color,n=14){for(let i=0;i<n;i++)particles.push({x,y,vx:(Math.random()-.5)*180,vy:(Math.random()-.5)*180,life:.5+Math.random()*.4,color,size:2+Math.random()*3})}
function collide(o,p){let x=cx+Math.cos(o.a)*o.r,y=cy+Math.sin(o.a)*o.r;return Math.hypot(x-p.x,y-p.y)<o.size+9}
function die(){if(shield>0){shield=0;let p=shipPos();burst(p.x,p.y,'#62f1ff',35);flash.classList.remove('go');void flash.offsetWidth;flash.classList.add('go');beep(160,.25,'sawtooth');objects=objects.filter(o=>!collide(o,p));return}state='dead';let p=shipPos();burst(p.x,p.y,'#ff385d',55);beep(85,.7,'sawtooth',.07);setTimeout(()=>{document.querySelector('.card .kicker').textContent='RUN TERMINATED';document.querySelector('.card h1').innerHTML=`${Math.floor(score).toLocaleString()}<span>POINTS</span>`;document.querySelector('.card p').innerHTML=`Wave ${wave} · Best ${best.toLocaleString()}<br>Tap launch and break orbit again.`;document.querySelector('#start').textContent='RELAUNCH';overlay.classList.remove('hidden')},650)}
function update(dt){stars.forEach(s=>{s.a+=dt*.4});particles.forEach(p=>{p.x+=p.vx*dt;p.y+=p.vy*dt;p.vx*=.97;p.vy*=.97;p.life-=dt});particles=particles.filter(p=>p.life>0);if(state!=='play')return;elapsed+=dt;wave=1+Math.floor(elapsed/18);ship.speed=1.6+wave*.09;ship.a+=ship.dir*ship.speed*dt*(slow>0?.58:1);shield=Math.max(0,shield-dt);slow=Math.max(0,slow-dt);spawn-=dt;coreSpawn-=dt;if(spawn<=0){addObject('meteor');spawn=Math.max(.24,1.15-wave*.065)*(slow>0?1.5:1)}if(coreSpawn<=0){addObject(Math.random()<.16?'power':'core');coreSpawn=1.6+Math.random()*1.7}let p=shipPos();objects.forEach(o=>{o.a+=o.speed*dt*(slow>0?.55:1);o.spin+=dt*3;if(o.type==='meteor')o.r+=(ship.r-o.r)*dt*(.13+wave*.012);if(collide(o,p)){if(o.type==='meteor'){o.hit=true;die()}else{o.hit=true;combo++;let pts=(o.type==='power'?500:100)*Math.min(combo,10)*wave;score+=pts;burst(p.x,p.y,o.type==='power'?'#74ffb0':'#ffe768',18);if(o.type==='power'){if(o.kind==='shield')shield=9;else slow=7;beep(980,.18,'triangle')}else beep(720+combo*25,.06,'sine');}}});objects=objects.filter(o=>!o.hit&&o.r>-40&&o.r<Math.max(W,H));score+=dt*12*wave;updateHud()}
function glow(color,blur=18){ctx.shadowColor=color;ctx.shadowBlur=blur}
function draw(){ctx.clearRect(0,0,W,H);let grd=ctx.createRadialGradient(cx,cy,20,cx,cy,Math.max(W,H)*.65);grd.addColorStop(0,'#251553');grd.addColorStop(.36,'#0b0d29');grd.addColorStop(1,'#02030a');ctx.fillStyle=grd;ctx.fillRect(0,0,W,H);stars.forEach(s=>{ctx.globalAlpha=.3+.45*Math.sin(s.a);ctx.fillStyle='#d9e9ff';ctx.fillRect(s.x,s.y,s.s,s.s)});ctx.globalAlpha=1;
 let pg=ctx.createRadialGradient(cx-18*scale,cy-22*scale,4,cx,cy,70*scale);pg.addColorStop(0,'#f3bbff');pg.addColorStop(.28,'#9d43e2');pg.addColorStop(1,'#24145b');glow('#a83cff',30);ctx.fillStyle=pg;ctx.beginPath();ctx.arc(cx,cy,62*scale,0,7);ctx.fill();ctx.shadowBlur=0;ctx.strokeStyle=slow>0?'#75ffdf':'#533994';ctx.lineWidth=2;ctx.beginPath();ctx.arc(cx,cy,ship.r,0,7);ctx.stroke();
 objects.forEach(o=>{let x=cx+Math.cos(o.a)*o.r,y=cy+Math.sin(o.a)*o.r;ctx.save();ctx.translate(x,y);ctx.rotate(o.spin);if(o.type==='meteor'){glow('#ff314f',12);ctx.fillStyle='#ff3d57';ctx.beginPath();for(let i=0;i<10;i++){let a=i*Math.PI/5,r=o.size*(i%2?1:.58);ctx.lineTo(Math.cos(a)*r,Math.sin(a)*r)}ctx.closePath();ctx.fill()}else{let col=o.type==='power'?(o.kind==='shield'?'#62f1ff':'#78ffb4'):'#ffe75d';glow(col,20);ctx.fillStyle=col;ctx.rotate(Math.PI/4);ctx.fillRect(-o.size/1.5,-o.size/1.5,o.size*1.3,o.size*1.3);ctx.fillStyle='#fff';ctx.fillRect(-2,-2,4,4)}ctx.restore()});
 let p=shipPos();ctx.save();ctx.translate(p.x,p.y);ctx.rotate(ship.a+(ship.dir>0?Math.PI/2:-Math.PI/2));glow(shield>0?'#62f1ff':'#fff',shield>0?30:15);ctx.fillStyle='#fff';ctx.beginPath();ctx.moveTo(0,-13);ctx.lineTo(9,10);ctx.lineTo(0,6);ctx.lineTo(-9,10);ctx.closePath();ctx.fill();ctx.fillStyle='#65edff';ctx.fillRect(-3,7,6,9);if(shield>0){ctx.strokeStyle='#62f1ff';ctx.lineWidth=3;ctx.beginPath();ctx.arc(0,0,19,0,7);ctx.stroke()}ctx.restore();ctx.shadowBlur=0;
 particles.forEach(p=>{ctx.globalAlpha=Math.max(0,p.life*1.5);ctx.fillStyle=p.color;ctx.fillRect(p.x,p.y,p.size,p.size)});ctx.globalAlpha=1;if(combo>1&&state==='play'){ctx.textAlign='center';ctx.font='bold 15px ui-monospace';ctx.fillStyle='#ffe75d';ctx.fillText(`${Math.min(combo,10)}× CORE CHAIN`,cx,H-48)}}
function loop(t){let dt=Math.min(.033,(t-last)/1000||0);last=t;update(dt);draw();requestAnimationFrame(loop)}reset();state='ready';requestAnimationFrame(loop);
window.__orbitState=()=>({state,score,wave,ship:{a:ship?.a,dir:ship?.dir},objects:objects.map(o=>o.type),shield,slow});
