import * as THREE from 'https://cdn.jsdelivr.net/npm/three@0.160.0/build/three.module.js';
const stage=document.querySelector('#stage'),scoreEl=document.querySelector('#score'),sectorEl=document.querySelector('#sector'),healthEl=document.querySelector('#health'),statusEl=document.querySelector('#status'),overlay=document.querySelector('#overlay'),titleEl=document.querySelector('#title'),chapterEl=document.querySelector('#chapter'),storyEl=document.querySelector('#story'),startBtn=document.querySelector('#start'),tx=document.querySelector('#tx'),speaker=document.querySelector('#speaker'),words=document.querySelector('#words'),novaBtn=document.querySelector('#nova'),chargeEl=document.querySelector('#charge'),damage=document.querySelector('#damage');
let scene,camera,renderer,clock,ship,shipCore,stars,planet,enemies=[],shots=[],enemyShots=[],debris=[],pickups=[],score=0,hull=100,shield=0,nova=0,sector=1,state='intro',elapsed=0,spawn=0,fire=0,boss=null,bossDefeated=false,target={x:0,y:0},pointer=false,storyStep=0,audio,best=+(localStorage.starfallBest||0),kills=0;
const chapters=[
 {at:0,sector:1,speaker:'COMMAND // ADMIRAL SATO',words:'Vance, the signal originates beneath Earth’s defense lattice. Nothing human has crossed it in seventeen years.'},
 {at:12,sector:2,speaker:'UNKNOWN SIGNAL',words:'Mara... if you can hear me, do not trust the stars. They are watching through them.'},
 {at:27,sector:3,speaker:'SHIP AI // ORPHEUS',words:'The signal is authentic. Voiceprint match: Doctor Elara Vance. Probability of survival after seventeen years: impossible.'},
 {at:43,sector:4,speaker:'ELARA VANCE',words:'I did not survive, Mara. I became the lock. And something on this side has finally found the key.'},
 {at:60,sector:5,speaker:'THE WARDEN',words:'LAST PILOT OF EARTH. BRING US THE LIGHT YOU CARRY.'}
];
function init(){scene=new THREE.Scene();scene.fog=new THREE.FogExp2(0x02040d,.018);camera=new THREE.PerspectiveCamera(65,innerWidth/innerHeight,.1,500);camera.position.set(0,3,15);renderer=new THREE.WebGLRenderer({antialias:true,powerPreference:'high-performance'});renderer.setPixelRatio(Math.min(devicePixelRatio,1.7));renderer.setSize(innerWidth,innerHeight);renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.3;stage.appendChild(renderer.domElement);clock=new THREE.Clock();
 scene.add(new THREE.HemisphereLight(0x7799ff,0x150525,1.8));let sun=new THREE.DirectionalLight(0xffc57a,3);sun.position.set(-5,6,8);scene.add(sun);let rim=new THREE.PointLight(0x32ddff,40,50);rim.position.set(5,0,5);scene.add(rim);makeShip();makeSpace();resize();addEventListener('resize',resize);renderer.setAnimationLoop(loop)}
function makeShip(){ship=new THREE.Group();let dark=new THREE.MeshStandardMaterial({color:0x182343,metalness:.85,roughness:.22}),white=new THREE.MeshStandardMaterial({color:0xcbe8ff,metalness:.65,roughness:.18,emissive:0x123a66}),cyan=new THREE.MeshBasicMaterial({color:0x62efff});let body=new THREE.Mesh(new THREE.ConeGeometry(.48,2.8,8),white);body.rotation.x=-Math.PI/2;ship.add(body);let wingGeo=new THREE.BufferGeometry().setFromPoints([new THREE.Vector3(0,0,0),new THREE.Vector3(2.1,0,.9),new THREE.Vector3(.45,0,-1)]);let wing=new THREE.Mesh(wingGeo,dark),wing2=wing.clone();wing2.scale.x=-1;ship.add(wing,wing2);shipCore=new THREE.Mesh(new THREE.SphereGeometry(.19,12,8),cyan);shipCore.position.z=.8;ship.add(shipCore);for(let x of[-.3,.3]){let eng=new THREE.Mesh(new THREE.CylinderGeometry(.12,.22,.7,10),cyan);eng.rotation.x=Math.PI/2;eng.position.set(x,-.05,1.25);ship.add(eng)}ship.position.z=3;scene.add(ship)}
function makeSpace(){let pos=[];for(let i=0;i<1800;i++)pos.push((Math.random()-.5)*180,(Math.random()-.5)*110,-Math.random()*360+20);let g=new THREE.BufferGeometry();g.setAttribute('position',new THREE.Float32BufferAttribute(pos,3));stars=new THREE.Points(g,new THREE.PointsMaterial({color:0xbad8ff,size:.18,transparent:true,opacity:.85}));scene.add(stars);planet=new THREE.Mesh(new THREE.IcosahedronGeometry(13,3),new THREE.MeshStandardMaterial({color:0x172458,emissive:0x081332,roughness:.8}));planet.position.set(-22,14,-90);scene.add(planet);let ring=new THREE.Mesh(new THREE.TorusGeometry(18,.08,8,100),new THREE.MeshBasicMaterial({color:0x3ac8ff,transparent:true,opacity:.35}));ring.position.copy(planet.position);ring.rotation.x=1.25;scene.add(ring);for(let i=0;i<16;i++){let arch=new THREE.Mesh(new THREE.TorusGeometry(10+i*.9,.035,5,70),new THREE.MeshBasicMaterial({color:i%2?0x3159ff:0x7e31ff,transparent:true,opacity:.16}));arch.position.z=-20-i*17;arch.scale.y=.62;scene.add(arch)}}
function resize(){camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight)}
function mat(color,emissive=color){return new THREE.MeshStandardMaterial({color,emissive,emissiveIntensity:.8,metalness:.5,roughness:.3})}
function spawnEnemy(type='drone'){let g=new THREE.Group(),body;if(type==='boss'){body=new THREE.Mesh(new THREE.OctahedronGeometry(3.3,1),mat(0x351044,0xff174f));for(let i=0;i<6;i++){let arm=new THREE.Mesh(new THREE.ConeGeometry(.55,4,5),mat(0x17172f,0x5e126d));arm.rotation.z=i*Math.PI/3;arm.position.set(Math.cos(i*Math.PI/3)*3.3,Math.sin(i*Math.PI/3)*3.3,0);g.add(arm)}g.hp=180;g.isBoss=true;boss=g}else{body=new THREE.Mesh(new THREE.OctahedronGeometry(.65,0),mat(type==='hunter'?0xff3a62:0x8b4cff));g.hp=type==='hunter'?4:2;for(let s of[-1,1]){let wing=new THREE.Mesh(new THREE.ConeGeometry(.25,1.5,4),mat(0x161936,0x4411aa));wing.rotation.z=s*1.1;wing.position.x=s*.8;g.add(wing)}}g.add(body);g.position.set((Math.random()-.5)*12,(Math.random()-.5)*10,type==='boss'?-95:-75-Math.random()*40);g.userData={type,phase:Math.random()*6.2,fire:1+Math.random()*2};scene.add(g);enemies.push(g);return g}
function laser(from,enemy=false){let mesh=new THREE.Mesh(new THREE.CylinderGeometry(enemy?.07:.045,enemy?.07:.045,enemy?1.2:2.5,6),new THREE.MeshBasicMaterial({color:enemy?0xff3157:0x68efff}));mesh.rotation.x=Math.PI/2;mesh.position.copy(from);scene.add(mesh);(enemy?enemyShots:shots).push(mesh);if(!enemy)beep(500,.025,'square',.012)}
function explode(pos,color=0xff476d,count=18){for(let i=0;i<count;i++){let m=new THREE.Mesh(new THREE.TetrahedronGeometry(.08+Math.random()*.16),new THREE.MeshBasicMaterial({color}));m.position.copy(pos);m.userData.v=new THREE.Vector3((Math.random()-.5)*12,(Math.random()-.5)*12,(Math.random()-.5)*12);m.userData.life=.5+Math.random()*.6;scene.add(m);debris.push(m)}}
function spawnPickup(pos){let p=new THREE.Mesh(new THREE.IcosahedronGeometry(.36,0),new THREE.MeshStandardMaterial({color:0xffd348,emissive:0xff8a00,emissiveIntensity:2}));p.position.copy(pos);p.userData.kind=Math.random()<.4?'shield':'nova';scene.add(p);pickups.push(p)}
function initAudio(){if(!audio)audio=new (window.AudioContext||window.webkitAudioContext)();if(audio.state==='suspended')audio.resume()}
function beep(f,d=.05,type='sine',v=.03){if(!audio)return;let o=audio.createOscillator(),g=audio.createGain();o.type=type;o.frequency.value=f;g.gain.setValueAtTime(v,audio.currentTime);g.gain.exponentialRampToValueAtTime(.0001,audio.currentTime+d);o.connect(g).connect(audio.destination);o.start();o.stop(audio.currentTime+d)}
function begin(){initAudio();enemies.forEach(x=>scene.remove(x));shots.concat(enemyShots,debris,pickups).forEach(x=>scene.remove(x));enemies=[];shots=[];enemyShots=[];debris=[];pickups=[];score=0;hull=100;shield=0;nova=0;sector=1;elapsed=0;spawn=.5;fire=0;storyStep=0;kills=0;boss=null;bossDefeated=false;state='play';target={x:0,y:0};overlay.classList.add('hidden');transmit(chapters[0]);storyStep=1;updateHud()}
startBtn.onclick=begin;
function transmit(c){speaker.textContent=c.speaker;words.textContent=c.words;tx.classList.add('show');setTimeout(()=>tx.classList.remove('show'),5200)}
function updateHud(){scoreEl.textContent=Math.floor(score).toLocaleString();sectorEl.textContent=String(sector).padStart(2,'0');healthEl.style.width=Math.max(0,hull)+'%';statusEl.textContent=shield?`${Math.ceil(hull)}% + SHIELD`:`${Math.ceil(hull)}%`;chargeEl.textContent=Math.floor(nova)+'%';novaBtn.classList.toggle('ready',nova>=100);localStorage.starfallBest=Math.max(best,score)}
function hit(d=18){if(shield>0){shield=Math.max(0,shield-d*1.5);beep(180,.12,'sawtooth');return}hull-=d;damage.classList.remove('hit');void damage.offsetWidth;damage.classList.add('hit');beep(90,.25,'sawtooth',.06);if(hull<=0)end(false)}
function end(win){state=win?'won':'dead';best=Math.max(best,Math.floor(score));localStorage.starfallBest=best;setTimeout(()=>{overlay.classList.remove('hidden');if(win){titleEl.innerHTML='DAWN<span>RETURNS</span>';chapterEl.textContent='EPILOGUE · THE FIRST MORNING';storyEl.textContent='Elara’s last signal was never a plea for rescue. It was a weapon—and you carried it through the Warden. Across Earth, seventeen years of night end at once. Humanity hears birds before it hears your name.';startBtn.textContent='FLY THE STORY AGAIN'}else{titleEl.innerHTML='SIGNAL<span>LOST</span>';chapterEl.textContent=`SECTOR ${sector} · SCORE ${Math.floor(score).toLocaleString()}`;storyEl.textContent='The dark closes over your fighter. Somewhere beneath Earth, Elara keeps transmitting. The signal will wait for you.';startBtn.textContent='RELAUNCH'}} ,700)}
function destroyEnemy(e){if(e.dead)return;e.dead=true;kills++;score+=e.isBoss?25000:500*sector;nova=Math.min(100,nova+(e.isBoss?100:12));explode(e.position,e.isBoss?0xffd044:0xa65cff,e.isBoss?90:22);if(!e.isBoss&&Math.random()<.16)spawnPickup(e.position);if(e.isBoss){boss=null;bossDefeated=true;transmit({speaker:'ELARA VANCE',words:'You found me, Mara. Now finish what I began. Let there be morning.'});setTimeout(()=>end(true),1800)}}
function novaBlast(){if(state!=='play'||nova<100)return;nova=0;beep(70,.55,'sawtooth',.07);let pulse=new THREE.PointLight(0x89ffff,150,80);pulse.position.copy(ship.position);scene.add(pulse);setTimeout(()=>scene.remove(pulse),350);enemies.slice().forEach(e=>{e.hp-=e.isBoss?35:99;explode(e.position,0x65eeff,10);if(e.hp<=0)destroyEnemy(e)});enemyShots.forEach(x=>scene.remove(x));enemyShots=[];updateHud()}
novaBtn.addEventListener('pointerdown',e=>{e.stopPropagation();novaBlast()});
function aim(e){let x=e.clientX/innerWidth*2-1,y=-(e.clientY/innerHeight*2-1);target.x=THREE.MathUtils.clamp(x*7,-7,7);target.y=THREE.MathUtils.clamp(y*6,-5.5,5.5)}
stage.addEventListener('pointerdown',e=>{pointer=true;aim(e)});stage.addEventListener('pointermove',e=>{if(pointer)aim(e)});addEventListener('pointerup',()=>pointer=false);
function update(dt){debris.forEach(d=>{d.position.addScaledVector(d.userData.v,dt);d.rotation.x+=dt*5;d.userData.life-=dt});debris.filter(d=>d.userData.life<=0).forEach(d=>scene.remove(d));debris=debris.filter(d=>d.userData.life>0);if(state!=='play')return;elapsed+=dt;sector=Math.min(5,1+Math.floor(elapsed/15));if(storyStep<chapters.length&&elapsed>=chapters[storyStep].at){transmit(chapters[storyStep]);storyStep++}ship.position.x=THREE.MathUtils.damp(ship.position.x,target.x,7,dt);ship.position.y=THREE.MathUtils.damp(ship.position.y,target.y,7,dt);ship.rotation.z=THREE.MathUtils.damp(ship.rotation.z,-(target.x-ship.position.x)*.13,8,dt);ship.rotation.x=THREE.MathUtils.damp(ship.rotation.x,(target.y-ship.position.y)*.06,8,dt);camera.position.x=THREE.MathUtils.damp(camera.position.x,ship.position.x*.16,3,dt);camera.position.y=THREE.MathUtils.damp(camera.position.y,3+ship.position.y*.1,3,dt);stars.position.z=(stars.position.z+dt*24)%20;planet.rotation.y+=dt*.03;
 fire-=dt;if(fire<=0){laser(ship.position);fire=Math.max(.09,.23-sector*.025)}spawn-=dt;if(spawn<=0&&!boss&&!bossDefeated){spawnEnemy(Math.random()<sector*.08?'hunter':'drone');spawn=Math.max(.32,1.1-sector*.13)}if(elapsed>60&&!boss&&!bossDefeated)spawnEnemy('boss');
 shots.forEach(s=>s.position.z-=dt*95);enemyShots.forEach(s=>s.position.z+=dt*32);enemies.forEach(e=>{e.userData.phase+=dt;e.position.z+=dt*(e.isBoss?7:14+sector*1.8);if(!e.isBoss){e.position.x+=Math.sin(e.userData.phase*2)*dt*1.7;e.position.y+=Math.cos(e.userData.phase*1.7)*dt*1.2}else{e.position.x=Math.sin(elapsed*.65)*4;e.position.y=Math.cos(elapsed*.48)*2;e.rotation.z+=dt*.25}e.userData.fire-=dt;if(e.userData.fire<=0&&e.position.z>-55){laser(e.position,true);e.userData.fire=e.isBoss?.32:1.6+Math.random()*1.5}});
 for(let s of shots)for(let e of enemies)if(!s.hit&&!e.dead&&s.position.distanceTo(e.position)<(e.isBoss?3.7:1)){s.hit=true;e.hp--;if(e.hp<=0)destroyEnemy(e)}
 enemyShots.forEach(s=>{if(!s.hit&&s.position.distanceTo(ship.position)<.65){s.hit=true;hit(12)}});enemies.forEach(e=>{if(!e.dead&&e.position.distanceTo(ship.position)<(e.isBoss?3.3:1)){e.dead=true;hit(e.isBoss?45:25);explode(e.position)}});pickups.forEach(p=>{p.position.z+=dt*12;p.rotation.x+=dt*2;p.rotation.y+=dt*3;if(!p.hit&&p.position.distanceTo(ship.position)<.8){p.hit=true;if(p.userData.kind==='shield')shield=50;else nova=Math.min(100,nova+45);score+=1000;beep(900,.18,'triangle')}});
 shots.filter(s=>s.hit||s.position.z<-130).forEach(s=>scene.remove(s));enemyShots.filter(s=>s.hit||s.position.z>25).forEach(s=>scene.remove(s));pickups.filter(p=>p.hit||p.position.z>20).forEach(p=>scene.remove(p));enemies.filter(e=>e.dead||e.position.z>22).forEach(e=>{scene.remove(e);if(!e.dead&&e.position.z>22)hit(e.isBoss?30:8)});shots=shots.filter(s=>!s.hit&&s.position.z>-130);enemyShots=enemyShots.filter(s=>!s.hit&&s.position.z<25);pickups=pickups.filter(p=>!p.hit&&p.position.z<20);enemies=enemies.filter(e=>!e.dead&&e.position.z<=22);score+=dt*20*sector;updateHud()}
function loop(){let dt=Math.min(clock.getDelta(),.033);update(dt);shipCore.scale.setScalar(1+Math.sin(performance.now()*.02)*.2);renderer.render(scene,camera)}
window.__starfall={state:()=>({state,score,hull,shield,nova,sector,elapsed,enemies:enemies.length,shots:shots.length,boss:!!boss}),begin,spawnEnemy,novaBlast,forceBoss:()=>{elapsed=61;spawnEnemy('boss')},testEnemy:()=>{let e=spawnEnemy();e.position.set(ship.position.x,ship.position.y,ship.position.z-4);return e.uuid},chargeNova:()=>{nova=100;updateHud()},testHit:()=>hit(12)};
init();updateHud();
