/* Prism Rally's entirely procedural, low-resolution perspective renderer. */
const TAU=Math.PI*2;
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
const mix=(a,b,t)=>a+(b-a)*t;
function rgb(hex,fallback='#548d65'){hex=typeof hex==='string'?hex:fallback;if(hex.startsWith('#')){let v=hex.slice(1);if(v.length===3)v=v.split('').map(c=>c+c).join('');const n=parseInt(v,16);return[n>>16&255,n>>8&255,n&255];}return rgb(fallback);}
const color=(v,fall)=>typeof v==='string'?v:fall;
export class Renderer{
 constructor(canvas){this.canvas=canvas;this.ctx=canvas.getContext('2d',{alpha:false});this.buffer=document.createElement('canvas');this.buffer.width=480;this.buffer.height=270;this.b=this.buffer.getContext('2d',{alpha:false});this.W=480;this.H=270;this.map=null;this.lastTrack=null;this.frame=0;this.resize();}
 resize(){const d=Math.min(window.devicePixelRatio||1,2);this.canvas.width=Math.round(this.canvas.clientWidth*d)||960;this.canvas.height=Math.round(this.canvas.clientHeight*d)||540;this.ctx.imageSmoothingEnabled=false;}
 buildMap(track){const p=track.points;const xs=p.map(p=>p.x),ys=p.map(p=>p.y);const w=track.width||130;this.bounds={x:Math.min(...xs)-w*4,y:Math.min(...ys)-w*4};const span=Math.max(Math.max(...xs)-this.bounds.x,Math.max(...ys)-this.bounds.y)+w*4;this.mapScale=1536/span;const k=this.mapScale,ox=this.bounds.x,oy=this.bounds.y;const c=document.createElement('canvas');c.width=c.height=1536;const g=c.getContext('2d',{willReadFrequently:true});const data=track.data||{};g.fillStyle=color(data.ground,'#427f58');g.fillRect(0,0,1536,1536);
 // Speckled turf and broad checker patches give the road convincing velocity.
 for(let y=0;y<1536;y+=24)for(let x=0;x<1536;x+=24){g.fillStyle=(x/24+y/24)%2?'#ffffff07':'#00000006';g.fillRect(x,y,24,24);}
 let seed=19;const rand=()=>{seed=(seed*16807)%2147483647;return seed/2147483647;};for(let i=0;i<10000;i++){g.fillStyle=i%2?'#ffffff10':'#00000012';g.fillRect(rand()*1536,rand()*1536,1+rand()*3,1+rand()*2);}
 const path=()=>{g.beginPath();p.forEach((q,i)=>{const x=(q.x-ox)*k,y=(q.y-oy)*k;i?g.lineTo(x,y):g.moveTo(x,y);});g.closePath();};g.lineJoin='round';g.lineCap='round';path();g.strokeStyle='#24333266';g.lineWidth=(w+25)*k;g.stroke();path();g.strokeStyle='#f5e9bc';g.lineWidth=(w+9)*k;g.stroke();path();g.strokeStyle=color(data.road,'#444951');g.lineWidth=w*k;g.stroke();
 // Branch roads provide visible, physically driveable shortcuts.
 for(const br of track.branches||[]){g.beginPath();br.points.forEach((q,i)=>i?g.lineTo((q.x-ox)*k,(q.y-oy)*k):g.moveTo((q.x-ox)*k,(q.y-oy)*k));g.strokeStyle='#e9d9b9';g.lineWidth=w*.7*k;g.stroke();g.strokeStyle=color(data.road,'#444951');g.lineWidth=w*.64*k;g.stroke();}
 // Alternating outside kerb blocks.
 for(let s=0;s<track.length;s+=15){const q=track.at(s);for(const sign of[-1,1]){g.save();g.translate((q.x-ox)*k,(q.y-oy)*k);g.rotate(q.angle);g.fillStyle=Math.floor(s/15)%2?'#f5eacb':'#df726a';g.fillRect(-8*k,sign*w*.49*k-3*k,17*k,6*k);g.restore();}}
 g.setLineDash([12*k,21*k]);path();g.lineWidth=1.6*k;g.strokeStyle='#e8e3cf77';g.stroke();g.setLineDash([]);
 for(const z of data.surfaces||[]){for(let s=z.from*track.length;s<z.to*track.length;s+=8){const q=track.at(s);g.save();g.translate((q.x-ox)*k,(q.y-oy)*k);g.rotate(q.angle);g.fillStyle=z.type==='ice'?'#aae9efaa':z.type==='sand'?'#d8b672aa':'#334957aa';g.fillRect(-5*k,-w*.46*k,10*k,w*.92*k);g.restore();}}
 for(const z of data.boostZones||[]){for(let s=z.from*track.length;s<z.to*track.length;s+=10){const q=track.at(s);g.save();g.translate((q.x-ox)*k,(q.y-oy)*k);g.rotate(q.angle);g.fillStyle='#23dccc';g.fillRect(-4*k,-w*.35*k,8*k,w*.7*k);g.fillStyle='#e8ffbc';g.beginPath();g.moveTo(-3*k,-w*.2*k);g.lineTo(4*k,0);g.lineTo(-3*k,w*.2*k);g.lineWidth=2*k;g.strokeStyle='#edffc0';g.stroke();g.restore();}}
 for(const z of data.jumpZones||[]){const q=track.at(z.from*track.length);g.save();g.translate((q.x-ox)*k,(q.y-oy)*k);g.rotate(q.angle);g.fillStyle='#f9bb53';g.fillRect(-7*k,-w*.43*k,14*k,w*.86*k);g.restore();}
 const start=track.at(0);g.save();g.translate((start.x-ox)*k,(start.y-oy)*k);g.rotate(start.angle);for(let i=0;i<10;i++)for(let j=0;j<3;j++){g.fillStyle=(i+j)%2?'#26363c':'#fff4d9';g.fillRect((j*4-6)*k,(i*w/10-w/2)*k,4*k,w/10*k);}g.restore();
 this.map=g.getImageData(0,0,1536,1536).data;this.mapCanvas=c;this.lastTrack=track;this.ground=rgb(data.ground);this.scenery=[];
 for(let s=0;s<track.length;s+=w*.75){const q=track.at(s);for(const sign of[-1,1]){const off=w*(.77+rand()*.9)*sign;this.scenery.push({x:q.x-Math.sin(q.angle)*off,y:q.y+Math.cos(q.angle)*off,type:data.theme==='desert'||data.theme==='canyon'?'cactus':data.theme==='snow'||data.theme==='ice'?'pine':['night','aurora','neon','moon','sky','volcano','rainbow'].includes(data.theme)?'crystal':data.theme==='coast'||data.theme==='harbor'?'palm':'tree',size:w*(.3+rand()*.3)});}}
 this.groundFrame=this.b.createImageData(this.W,this.H);
 }
 sky(time,data,angle=0){const g=this.b,W=this.W,H=this.H,sky=data?.sky;let top=Array.isArray(sky)?sky[0]:color(sky,'#72bad4'),bottom=Array.isArray(sky)?sky[1]:['neon','moon','aurora'].includes(data?.theme)?'#575b84':'#dfebce';const grad=g.createLinearGradient(0,0,0,H*.5);grad.addColorStop(0,top);grad.addColorStop(1,bottom);g.fillStyle=grad;g.fillRect(0,0,W,H);g.fillStyle='#fff6cd';g.beginPath();g.arc(365,43,19,0,TAU);g.fill();if(['neon','moon','aurora'].includes(data?.theme)){g.fillStyle='#eff5ff';for(let i=0;i<55;i++)g.fillRect((i*137+19)%480,(i*41+7)%83,1,1);g.fillStyle=top;g.beginPath();g.arc(372,37,17,0,TAU);g.fill()}if(data?.theme==='aurora'){for(let i=0;i<3;i++){g.strokeStyle=['#8ef6c844','#bfa8ff44','#a9dbff44'][i];g.lineWidth=9;g.beginPath();for(let x=0;x<480;x+=8)g.lineTo(x,28+i*12+Math.sin(x*.015+time*.12+i)*13);g.stroke()}}if(data?.theme==='rainbow'){for(let i=0;i<5;i++){g.strokeStyle=['#ffd36b','#ff8e88','#d2a7f2','#99d9f2','#9de4c4'][i];g.lineWidth=3;g.beginPath();g.arc(220,130,100+i*4,Math.PI,TAU);g.stroke()}}
 for(let layer=0;layer<3;layer++){g.fillStyle=layer===0?'#92b6b2':layer===1?'#729e99':color(data?.horizon,'#497f78');g.beginPath();g.moveTo(0,110);for(let x=0;x<=W+8;x+=8){const v=x+angle*(40+layer*15);g.lineTo(x,94-layer*2-Math.sin(v*.018+layer*2)*(14-layer*3)-Math.sin(v*.045+layer)*(5-layer));}g.lineTo(W,140);g.lineTo(0,140);g.fill();}
 g.fillStyle='#ffffefaa';for(let n=0;n<4;n++){let x=((n*153+time*2-angle*20)%650+650)%650-70;g.fillRect(x,25+n%2*27,38,5);g.fillRect(x+8,20+n%2*27,20,7);}
 }
 project(x,y,z=0){const dx=x-this.camera.x,dy=y-this.camera.y;const depth=dx*this.camera.cos+dy*this.camera.sin,side=-dx*this.camera.sin+dy*this.camera.cos;if(depth<12)return null;const scale=this.camera.focal/depth;return{x:240+side*scale,y:this.camera.horizon+(this.camera.height-z)*scale,scale,depth};}
 sprite(q,kind,size,tint,time=0,angle=0,animal='fox'){const g=this.b,x=Math.round(q.x),y=Math.round(q.y),s=q.scale*size;if(s<1||x<-s||x>480+s||y>350+s)return;g.save();g.translate(x,y);g.scale(s/32,s/32);g.fillStyle='#132e3260';g.beginPath();g.ellipse(0,0,15,4,0,0,TAU);g.fill();
 if(kind==='kart'){const side=Math.sin(angle);g.translate(0,-3);g.fillStyle='#152c35';g.fillRect(-15,-9,7,12);g.fillRect(8,-9,7,12);g.fillStyle='#0e2029';g.fillRect(-12,-17,6,8);g.fillRect(6,-17,6,8);g.fillStyle=tint||'#ffb255';g.fillRect(-11,-14,22,13);g.fillRect(-14,-11,28,7);g.fillStyle='#ffffff66';g.fillRect(-9,-13,18,3);g.fillStyle='#263747';g.fillRect(-6,-16,12,8);g.fillStyle=tint||'#ffb255';g.fillRect(-7+side*3,-24,14,12);if(animal==='rabbit'){g.fillRect(-6+side*3,-34,4,12);g.fillRect(2+side*3,-34,4,12)}else if(animal==='fox'||animal==='cat'||animal==='tiger'){g.beginPath();g.moveTo(-7+side*3,-23);g.lineTo(-7+side*3,-30);g.lineTo(-1+side*3,-23);g.fill();g.beginPath();g.moveTo(7+side*3,-23);g.lineTo(7+side*3,-30);g.lineTo(1+side*3,-23);g.fill()}else if(animal==='robot'){g.fillRect(-1,-29,2,5);g.fillStyle='#ff7268';g.fillRect(-2,-31,4,3)}else{g.fillRect(-9,-24,5,5);g.fillRect(4,-24,5,5)}g.fillStyle='#f9dbb1';g.fillRect(-5+side*4,-20,10,6);g.fillStyle='#28444b';g.fillRect(-5+side*5,-20,10,3);g.fillStyle='#fff5c6';g.fillRect(-11,-4,5,2);g.fillRect(6,-4,5,2);g.fillStyle='#364a51';g.fillRect(-4,-1,8,3);
 }else if(kind==='item'||kind==='box'){g.translate(0,-8-Math.sin(time*3)*3);g.rotate(Math.sin(time)*.08);g.fillStyle='#fff5d0';g.fillRect(-11,-25,22,22);g.fillStyle='#9475dc';g.fillRect(-9,-23,18,18);g.fillStyle='#c5b7f1';g.fillRect(-8,-22,16,3);g.fillStyle='#fff6d9';g.font='bold 17px monospace';g.textAlign='center';g.fillText('?',0,-7);
 }else if(kind==='palm'){g.fillStyle='#a18155';g.fillRect(-2,-35,5,35);g.fillStyle='#3b9174';for(let i=0;i<5;i++){g.save();g.translate(0,-33);g.rotate(i*1.25);g.fillRect(0,-3,19,5);g.fillRect(13,0,8,4);g.restore()}}else if(kind==='tree'||kind==='pine'){g.fillStyle='#806452';g.fillRect(-3,-23,6,23);g.fillStyle=kind==='pine'?'#45756b':'#246458';g.beginPath();g.moveTo(0,-45);g.lineTo(-18,-13);g.lineTo(18,-13);g.fill();g.fillStyle=kind==='pine'?'#dbeede':'#46896a';g.beginPath();g.moveTo(0,-45);g.lineTo(-13,-23);g.lineTo(12,-23);g.fill();g.fillStyle='#72a278';g.fillRect(-6,-30,5,3);
 }else if(kind==='cactus'){g.fillStyle='#558972';g.fillRect(-4,-34,8,34);g.fillRect(-13,-23,7,5);g.fillRect(-13,-30,5,12);g.fillRect(7,-18,7,5);g.fillRect(10,-25,5,12);g.fillStyle='#9ab773';g.fillRect(-3,-31,2,27);
 }else if(kind==='crystal'){g.fillStyle='#8ecedd';g.beginPath();g.moveTo(0,-37);g.lineTo(-12,-17);g.lineTo(-7,-1);g.lineTo(8,-1);g.lineTo(12,-17);g.fill();g.fillStyle='#bdeddf';g.beginPath();g.moveTo(0,-37);g.lineTo(1,-2);g.lineTo(-12,-17);g.fill();
 }else if(['bolt','seeker','pulse'].includes(kind)){g.fillStyle=kind==='seeker'?'#e6b2ff':'#ffdc66';g.beginPath();g.arc(0,-8,7,0,TAU);g.fill();g.fillStyle='#fff4dd';g.fillRect(-3,-11,6,6)}else if(kind==='trap'){g.fillStyle='#d064a7';g.beginPath();g.ellipse(0,-1,16,6,0,0,TAU);g.fill()}else{g.fillStyle=kind==='oil'?'#263441':kind==='banana'?'#ffd667':'#837d75';g.beginPath();g.moveTo(-13,-3);g.lineTo(-10,-13);g.lineTo(3,-19);g.lineTo(12,-11);g.lineTo(15,-2);g.fill();g.fillStyle='#ffffff30';g.fillRect(-6,-12,9,3);}
 g.restore();}
 render(race,dt=0,settings={}){if(!race?.track?.points||!race.racers?.length){this.menu(race?.time||0);return;}if(this.lastTrack!==race.track)this.buildMap(race.track);this.activeRace=true;const g=this.b,p=race.racers[0],track=race.track,t=race.time||0,w=track.width||130;const angle=p.angle||0,back=w*.76,height=w*.46;this.camera={x:p.x-Math.cos(angle)*back,y:p.y-Math.sin(angle)*back,cos:Math.cos(angle),sin:Math.sin(angle),height:height+(p.z||0)*.32,focal:248,horizon:94};this.sky(t,track.data,angle);
 const im=this.groundFrame,arr=im.data,map=this.map,k=this.mapScale,ox=this.bounds.x,oy=this.bounds.y,far=w*24;const bg=this.ground;
 for(let y=95;y<270;y++){const depth=this.camera.height*248/(y-94);const step=depth/248,baseX=this.camera.x+this.camera.cos*depth+this.camera.sin*240*step,baseY=this.camera.y+this.camera.sin*depth-this.camera.cos*240*step;const fog=clamp((depth-w*5)/(far-w*5),0,.88);for(let x=0;x<480;x++){let tx=((baseX-this.camera.sin*x*step-ox)*k)|0,ty=((baseY+this.camera.cos*x*step-oy)*k)|0;let i=(y*480+x)*4;let m=(ty*1536+tx)*4;const valid=tx>=0&&tx<1536&&ty>=0&&ty<1536;arr[i]=mix(valid?map[m]:bg[0],166,fog);arr[i+1]=mix(valid?map[m+1]:bg[1],195,fog);arr[i+2]=mix(valid?map[m+2]:bg[2],175,fog);arr[i+3]=255;}}
 g.putImageData(im,0,0,0,95,480,175);
 const objects=[];for(const o of this.scenery){const q=this.project(o.x,o.y);if(q&&q.depth<far&&Math.abs(q.x-240)<300)objects.push({o,q});}for(const o of race.obstacles||[]){const q=this.project(o.x,o.y);if(q&&!(o.type==='timed'&&Math.sin(t*1.5)<0))objects.push({o:{...o,size:w*.17},q});}for(const o of race.items||[]){if(o.active===false)continue;const q=this.project(o.x,o.y);if(q)objects.push({o:{...o,type:'item',size:w*.18},q});}for(const o of race.projectiles||[]){const q=this.project(o.x,o.y);if(q)objects.push({o:{...o,size:w*.13},q});}for(const r of race.racers){const q=this.project(r.x,r.y,r.z||0);if(q)objects.push({o:{...r,type:'kart',size:w*.25},q,r});}if(race.ghost?.length){const gh=race.ghost;let i=gh.findIndex(v=>v[0]>=t);if(i>0){const a=gh[i-1],b=gh[i],u=(t-a[0])/(b[0]-a[0]||1);const q=this.project(mix(a[1],b[1],u),mix(a[2],b[2],u),mix(a[4]||0,b[4]||0,u));if(q)objects.push({o:{type:'kart',size:w*.25,color:'#b5ffff',angle:a[3],ghost:true},q});}}objects.sort((a,b)=>b.q.depth-a.q.depth);
 for(const {o,q,r}of objects){if(r?.boost>0){g.fillStyle='#6affea';const s=q.scale*w*.25;g.beginPath();g.moveTo(q.x-s*.22,q.y);g.lineTo(q.x,q.y+s*(.35+Math.sin(t*45)*.1));g.lineTo(q.x+s*.22,q.y);g.fill();}if(r?.shield>0){g.strokeStyle='#b0ffedaa';g.lineWidth=2;g.beginPath();g.ellipse(q.x,q.y-q.scale*w*.1,q.scale*w*.17,q.scale*w*.19,0,0,TAU);g.stroke();}g.globalAlpha=o.ghost?.35:1;this.sprite(q,o.type,o.size,o.color||o.character?.color||o.character?.palette?.[0],t,(o.angle||0)-angle,o.character?.animal);g.globalAlpha=1;if(r?.driftCharge>0){g.fillStyle=r.driftCharge>1?'#ffe48c':'#80fff3';for(const side of[-1,1])g.fillRect(q.x+side*q.scale*w*.11,q.y+Math.sin(t*30)*2,3,2);}}
 // Subtle vignette and speed streaks keep the center of the course readable.
 if((p.boost||0)>0){g.strokeStyle='#f7ffed66';for(let i=0;i<8;i++){const a=i/8*TAU;g.beginPath();g.moveTo(240+Math.cos(a)*175,135+Math.sin(a)*100);g.lineTo(240+Math.cos(a)*255,135+Math.sin(a)*170);g.stroke();}}
 if(p.hit>0&&!settings.reducedFlash){g.fillStyle='#ff765317';g.fillRect(0,0,480,270)}this.minimap(race);this.blit(p.hit>0&&!settings.reducedShake?Math.sin(t*80)*2:0);this.frame++;}
 minimap(race){const g=this.b,track=race.track,b=this.bounds,k=this.mapScale/1536*79;g.save();g.translate(383,190);g.fillStyle='#142d3acc';g.beginPath();g.roundRect(0,0,88,70,8);g.fill();g.strokeStyle='#ffffff22';g.lineWidth=1;g.stroke();g.translate(4,-5);g.beginPath();track.points.forEach((p,i)=>i?g.lineTo((p.x-b.x)*k,(p.y-b.y)*k):g.moveTo((p.x-b.x)*k,(p.y-b.y)*k));g.closePath();g.strokeStyle='#afc2c4';g.lineWidth=2.5;g.stroke();for(let i=race.racers.length-1;i>=0;i--){const p=race.racers[i];g.fillStyle=i?'#f1c084':'#ffffff';g.beginPath();g.arc((p.x-b.x)*k,(p.y-b.y)*k,i?1.5:2.5,0,TAU);g.fill();}g.restore();}
 blit(shake=0){this.ctx.imageSmoothingEnabled=false;const scale=Math.max(this.canvas.width/480,this.canvas.height/270);this.ctx.drawImage(this.buffer,(this.canvas.width-480*scale)/2+shake,0,480*scale,270*scale);if(this.canvas.width/this.canvas.height<1.25&&this.activeRace){const d=this.canvas.width/(this.canvas.clientWidth||390);this.ctx.drawImage(this.buffer,383,190,88,70,this.canvas.width-112*d,this.canvas.height-192*d,100*d,80*d);}}
 menu(time=0){this.activeRace=false;const g=this.b;this.sky(time,{},.15*Math.sin(time*.12));g.fillStyle='#588768';g.fillRect(0,103,480,167);for(let y=104;y<270;y++){const d=90/(y-95),center=240+Math.sin(d*.17+time*.1)*45,width=(y-94)*1.48;g.fillStyle='#e4d9b1';g.fillRect(center-width/2-4,y,width+8,1);g.fillStyle='#404b51';g.fillRect(center-width/2,y,width,1);if((Math.floor(d*5-time*9))%3===0){g.fillStyle='#e7dfb8';g.fillRect(center-1,y,2+(y-94)*.01,1);}}
 for(let i=0;i<8;i++){const d=(i*23+time*12)%185;const q={x:240+(i%2?1:-1)*(35+d*.8),y:105+d*.9,scale:.25+d*.008};this.sprite(q,'tree',34,null,time);}this.sprite({x:278,y:226,scale:2.3},'kart',32,'#f5b667',time);this.blit();}
}
