import {Track,wrap,angleDiff} from './track.js';
import {RACERS,DIFFICULTIES} from './data.js';
export const STEP=1/60, SCORE=[15,12,10,8,6,4,2,1];
export const ITEMS=[{id:'bolt',name:'Comet Bolt',icon:'✦',help:'Straight shot · nearest kart in front'},{id:'trap',name:'Jam Jar',icon:'◉',help:'Drops a slowing puddle behind you'},{id:'boost',name:'Solar Soda',icon:'»',help:'A two-second burst of speed'},{id:'shield',name:'Bubble Guard',icon:'◇',help:'Blocks hits for six seconds'},{id:'seeker',name:'Firefly',icon:'✧',help:'Homes toward the nearest racer ahead'},{id:'pulse',name:'Echo Bell',icon:'◎',help:'Slows rivals within 140 metres'}];
export function seeded(seed){return()=>{seed|=0;seed=seed+0x6D2B79F5|0;let t=Math.imul(seed^seed>>>15,1|seed);t=t+Math.imul(t^t>>>7,61|t)^t;return((t^t>>>14)>>>0)/4294967296}}
export function createRacer(character,index,track){let s=track.length-50-Math.floor(index/2)*32,p=track.at(s),o=(index%2?1:-1)*22;return {id:index,character,x:p.x-Math.sin(p.angle)*o,y:p.y+Math.cos(p.angle)*o,angle:p.angle,speed:0,z:0,vz:0,s,previousS:s,progress:0,lap:1,nextGate:0,passed:0,started:false,finished:false,finishTime:0,boost:0,shield:0,hit:0,immune:0,item:null,driftCharge:0,drifting:false,recovery:0,stuck:0,wrong:0,ai:index>0,offset:(index%3-1)*20,usedItems:0};}
export function checkpoint(r,oldS,newS,track){let delta=newS-oldS;if(delta<-track.length/2)delta+=track.length;if(delta>track.length/2)delta-=track.length;if(Math.abs(delta)>track.length/12)return;const spacing=track.length/track.gates;if(delta>0){const target=r.nextGate*spacing;let dist=wrap(target-oldS,track.length);if(dist<=delta+.01){if(!r.started){r.started=true;r.nextGate=1;r.progress=0;}else{r.passed++;r.nextGate=(r.nextGate+1)%track.gates;if(r.passed%track.gates===0){r.lap++;if(r.lap>3)r.finished=true}}}}r.progress=r.started?Math.max(0,r.passed*spacing+Math.min(spacing,wrap(newS-((r.nextGate+track.gates-1)%track.gates)*spacing,track.length))): -wrap(-newS,track.length);}
export class Race {
 constructor(data,{character=0,difficulty=0,mode='single',seed=12345,ghost=null}={}){this.track=new Track(data);this.difficulty=DIFFICULTIES[difficulty];this.classIndex=difficulty;this.mode=mode;this.random=seeded(seed);this.racers=Array.from({length:mode==='trial'||mode==='tutorial'?1:8},(_,i)=>createRacer(RACERS[(character+i)%8],i,this.track));this.player=this.racers[0];this.time=0;this.countdown=3.6;this.finished=false;this.finishOrder=[];this.events=[];this.projectiles=[];this.items=[];this.ghost=ghost;this.recording=[];this.recordTick=0;this.startArmed=false;this.startBurn=false;this.tutorial={drive:false,drift:false,item:false,finish:false};for(let i=0;i<12;i++){const s=(i+.5)/12*this.track.length,p=this.track.at(s);this.items.push({x:p.x,y:p.y,s,type:'box',active:true,cooldown:0})}this.obstacles=(data.obstacles||[]).map(o=>{let p=this.track.at(o.t*this.track.length);return {...o,x:p.x-Math.sin(p.angle)*o.offset*this.track.width,y:p.y+Math.cos(p.angle)*o.offset*this.track.width,baseX:p.x-Math.sin(p.angle)*o.offset*this.track.width,baseY:p.y+Math.cos(p.angle)*o.offset*this.track.width,angle:p.angle}});if(mode==='tutorial')this.player.item='boost';}
 emit(type){this.events.push(type)}
 ranking(){return [...this.racers].sort((a,b)=>a.finished&&b.finished?a.finishTime-b.finishTime:a.finished?-1:b.finished?1:b.progress-a.progress)}
 position(r){return this.ranking().indexOf(r)+1}
 aiInput(r){const near=this.track.nearest(r.x,r.y),look=70+Math.abs(r.speed)*(.45-this.classIndex*.05),p=this.track.at(near.s+look),o=r.offset;const target=Math.atan2(p.y+Math.cos(p.angle)*o-r.y,p.x-Math.sin(p.angle)*o-r.x),turn=angleDiff(target,r.angle);const bend=Math.abs(angleDiff(this.track.at(near.s+150).angle,near.angle));return {throttle:bend>1.1&&r.speed>135?.15:1,brake:Math.abs(turn)>1.1&&r.speed>100?.5:0,steer:Math.max(-1,Math.min(1,turn*2.4)),drift:Math.abs(turn)>(.32-this.classIndex*.05)&&Math.abs(turn)<.9,item:!!r.item&&this.random()<(.006+this.classIndex*.003),recover:false}}
 hitRacer(r,duration=1.1){if(r.immune>0||r.z>12)return false;if(r.shield>0){r.shield=0;r.immune=1;this.emit('shield');return false}r.hit=duration;r.immune=duration+2;r.speed*=.35;this.emit('hit');return true}
 giveItem(r){const pos=this.position(r),roll=this.random();r.item=pos<=2?['trap','shield','bolt','pulse'][Math.floor(roll*4)]:pos>=6?['boost','seeker','shield','boost','pulse'][Math.floor(roll*5)]:ITEMS[Math.floor(roll*6)].id;if(r===this.player)this.emit('pickup')}
 useItem(r){if(!r.item||r.finished)return;const type=r.item;r.item=null;r.usedItems++;if(r===this.player){this.tutorial.item=true;this.emit('item')}if(type==='boost')r.boost=2.2;else if(type==='shield')r.shield=6;else if(type==='pulse'){for(const q of this.racers)if(q!==r&&Math.hypot(q.x-r.x,q.y-r.y)<140)this.hitRacer(q,.9)}else if(type==='trap')this.projectiles.push({x:r.x-Math.cos(r.angle)*28,y:r.y-Math.sin(r.angle)*28,angle:r.angle,type,owner:r.id,ttl:12,age:0});else{const target=this.racers.filter(q=>q!==r&&!q.finished&&q.progress>r.progress).sort((a,b)=>a.progress-b.progress)[0];this.projectiles.push({x:r.x+Math.cos(r.angle)*24,y:r.y+Math.sin(r.angle)*24,angle:r.angle,type,owner:r.id,ttl:4,age:0,target:target?.id})}}
 recover(r){const s=r.started?((r.nextGate+this.track.gates-1)%this.track.gates)*this.track.length/this.track.gates+8:this.track.length-45,p=this.track.at(s);r.x=p.x;r.y=p.y;r.angle=p.angle;r.s=s;r.previousS=s;r.speed=0;r.z=0;r.vz=0;r.recovery=1.2;r.immune=3;r.stuck=0;if(r===this.player)this.emit('recover')}
 step(dt,input={}){this.events.length=0;if(this.finished&&this.racers.every(r=>r.finished))return;if(this.countdown>0){let previous=this.countdown;this.countdown-=dt;if(input.throttle&&previous>1.05)this.startBurn=true;if(!input.throttle&&previous>.45)this.startBurn=false;if(input.throttle&&previous<=1.05&&previous>.15&&!this.startBurn)this.startArmed=true;if(Math.ceil(previous)!==Math.ceil(this.countdown))this.emit('count');if(this.countdown<=0){if(this.startArmed)this.player.boost=1.5;this.emit('go')}return}this.time+=dt;
 for(const box of this.items){if(!box.active){box.cooldown-=dt;if(box.cooldown<=0)box.active=true}}
 for(const o of this.obstacles)if(o.type==='moving'||o.type==='sweeper'){let offset=Math.sin(this.time*1.3+o.t*40)*this.track.width*.32;o.x=o.baseX-Math.sin(o.angle)*offset;o.y=o.baseY+Math.cos(o.angle)*offset}
 for(const r of this.racers){if(r.finished)continue;const c=r.ai?this.aiInput(r):input;for(const key of ['boost','shield','hit','immune','recovery'])r[key]=Math.max(0,r[key]-dt);if(r.recovery>0)continue;if(c.recover)this.recover(r);const near=this.track.nearest(r.x,r.y),onRoad=near.distance<this.track.width/2,surface=this.track.surface(near.s),slip=surface==='ice'||surface==='slippery';let base=215+(r.character.stats.speed-3)*7;let max=base*(this.difficulty.speed||1);if(r.ai){max*=.86+(this.difficulty.ai||1)*.09+(r.id%3)*.012;const gap=this.player.progress-r.progress;max*=1+Math.max(-.025,Math.min(.035,gap/this.track.length*.12))}if(!onRoad)max*=.46;if(r.boost>0)max*=1.42;if(r.hit>0)max*=.35;if(surface==='mud'||surface==='sand')max*=.75;const acceleration=105+(r.character.stats.accel-3)*10;r.speed+=(c.throttle||0)*acceleration*dt;if(c.brake)r.speed-=170*c.brake*dt;if(!c.throttle&&!c.brake)r.speed*=Math.exp(-.7*dt);if(r.speed>max)r.speed=Math.max(max,r.speed-220*dt);r.speed=Math.max(-60,Math.min(max+10,r.speed));const steer=c.steer||0;const grip=slip?.65:1;r.angle+=steer*(1.15+r.character.stats.handling*.13)*(Math.min(1,Math.abs(r.speed)/70))*(r.speed<0?-1:1)*(c.drift?1.25:1)*(1/(1+Math.abs(r.speed)/250))*grip*dt;r.drifting=!!c.drift&&Math.abs(r.speed)>75&&Math.abs(steer)>.15&&onRoad;if(r.drifting){r.driftCharge=Math.min(2.3,r.driftCharge+dt);}else if(r.driftCharge>0){if(r.driftCharge>.7){r.boost=Math.max(r.boost,Math.min(1.6,r.driftCharge*.65));if(r===this.player){this.tutorial.drift=true;this.emit('boost')}}r.driftCharge=0}let travelAngle=r.angle-(r.drifting?steer*.22:0);r.x+=Math.cos(travelAngle)*r.speed*dt;r.y+=Math.sin(travelAngle)*r.speed*dt;
 if(onRoad&&this.track.zone(near.s,'boostZones'))r.boost=Math.max(r.boost,.3);if(onRoad&&this.track.zone(near.s,'jumpZones')&&r.z===0&&r.speed>100){r.vz=105;r.z=.1;this.emit('jump')}if(r.z>0){r.vz-=220*dt;r.z+=r.vz*dt;if(r.z<=0){r.z=0;r.vz=0;if(r===this.player)this.emit('land')}}for(const o of this.obstacles){if(o.type==='timed'&&Math.sin(this.time*1.5)<0)continue;if(r.z<14&&Math.hypot(r.x-o.x,r.y-o.y)<19){this.hitRacer(r,.7);let a=Math.atan2(r.y-o.y,r.x-o.x);r.x=o.x+Math.cos(a)*21;r.y=o.y+Math.sin(a)*21}}
 const current=this.track.nearest(r.x,r.y);r.s=current.s;checkpoint(r,r.previousS,r.s,this.track);r.previousS=r.s;r.wrong=Math.abs(angleDiff(r.angle,current.angle))>2&&Math.abs(r.speed)>30?r.wrong+dt:0;r.stuck=Math.abs(r.speed)<15?r.stuck+dt:0;if(current.distance>this.track.width*2.1||r.stuck>(r.ai?3:8)||r.ai&&r.wrong>2)this.recover(r);if(r.finished){r.finishTime=this.time;this.finishOrder.push(r.id);if(r===this.player){this.finished=true;this.tutorial.finish=true;this.emit('finish')}continue}for(const box of this.items)if(box.active&&!r.item&&Math.hypot(r.x-box.x,r.y-box.y)<35){this.giveItem(r);box.active=false;box.cooldown=4}if(c.item)this.useItem(r);if(r===this.player&&r.speed>50)this.tutorial.drive=true;
 }
 for(let i=0;i<this.racers.length;i++)for(let j=i+1;j<this.racers.length;j++){const a=this.racers[i],b=this.racers[j],dist=Math.hypot(a.x-b.x,a.y-b.y);if(dist<21&&dist>0&&Math.abs(a.z-b.z)<12){const dx=(a.x-b.x)/dist,dy=(a.y-b.y)/dist;a.x+=dx*(21-dist)*.5;a.y+=dy*(21-dist)*.5;b.x-=dx*(21-dist)*.5;b.y-=dy*(21-dist)*.5;a.speed*=.99;b.speed*=.99}}
 for(const p of this.projectiles){p.ttl-=dt;p.age+=dt;if(p.type!=='trap'){if(p.type==='seeker'&&p.target!==undefined){let q=this.racers[p.target];p.angle+=Math.max(-3*dt,Math.min(3*dt,angleDiff(Math.atan2(q.y-p.y,q.x-p.x),p.angle)))}p.x+=Math.cos(p.angle)*350*dt;p.y+=Math.sin(p.angle)*350*dt}for(const r of this.racers)if(r.id!==p.owner&&Math.hypot(r.x-p.x,r.y-p.y)<23){this.hitRacer(r);p.ttl=0;break}}this.projectiles=this.projectiles.filter(p=>p.ttl>0);if(this.mode==='trial'&&!this.player.finished&&(this.recordTick++%6===0))this.recording.push([+this.time.toFixed(2),+this.player.x.toFixed(1),+this.player.y.toFixed(1),+this.player.angle.toFixed(3),+this.player.z.toFixed(1)]);
 }
}
export function scoreChampionship(totals,ranking){for(let i=0;i<ranking.length;i++)totals[ranking[i].character.id]=(totals[ranking[i].character.id]||0)+SCORE[i];return totals}
export class FixedClock{constructor(){this.accumulator=0}advance(elapsed,step){this.accumulator+=Math.min(.25,elapsed);let count=0;while(this.accumulator+1e-10>=STEP&&count<15){step(STEP);this.accumulator-=STEP;count++}return count}reset(){this.accumulator=0}}
