export const wrap=(v,n)=>(v%n+n)%n;
export const angleDiff=(a,b)=>Math.atan2(Math.sin(a-b),Math.cos(a-b));
export class Track {
 constructor(data){this.data=data;this.width=data.width;this.points=[];let s=0;const p=data.points,n=p.length;for(let i=0;i<n;i++)for(let j=0;j<16;j++){let t=j/16;const a=p[wrap(i-1,n)],b=p[i],c=p[(i+1)%n],d=p[(i+2)%n];const f=k=>.5*((2*b[k])+(-a[k]+c[k])*t+(2*a[k]-5*b[k]+4*c[k]-d[k])*t*t+(-a[k]+3*b[k]-3*c[k]+d[k])*t*t*t);let q={x:f(0),y:f(1),s};if(this.points.length){const prev=this.points.at(-1);s+=Math.hypot(q.x-prev.x,q.y-prev.y);q.s=s}this.points.push(q)}const first=this.points[0],last=this.points.at(-1);this.length=s+Math.hypot(first.x-last.x,first.y-last.y);this.points.forEach((q,i)=>{const next=this.points[(i+1)%this.points.length];q.angle=Math.atan2(next.y-q.y,next.x-q.x)});this.gates=24;this.branches=(data.branches||[]).map(b=>({...b,points:[this.at(b.from*this.length),...b.points.map(p=>({x:p[0],y:p[1]})),this.at(b.to*this.length)]}));}
 at(s){s=wrap(s,this.length);let lo=0,hi=this.points.length-1;while(lo<hi){let m=Math.ceil((lo+hi)/2);if(this.points[m].s<=s)lo=m;else hi=m-1}let a=this.points[lo],b=this.points[(lo+1)%this.points.length];const len=(b.s||this.length)-a.s,t=(s-a.s)/len;return {x:a.x+(b.x-a.x)*t,y:a.y+(b.y-a.y)*t,angle:a.angle,s}}
 nearest(x,y){let best={distance:Infinity};const scan=(a,b,s0,s1,branch=false)=>{const dx=b.x-a.x,dy=b.y-a.y,ll=dx*dx+dy*dy;const t=Math.max(0,Math.min(1,((x-a.x)*dx+(y-a.y)*dy)/ll));const px=a.x+t*dx,py=a.y+t*dy,d=Math.hypot(x-px,y-py);if(d<best.distance)best={distance:d,s:wrap(s0+(s1-s0)*t,this.length),offset:((x-px)*-dy+(y-py)*dx)/Math.sqrt(ll),angle:Math.atan2(dy,dx),branch}};for(let i=0;i<this.points.length;i++){const a=this.points[i],b=this.points[(i+1)%this.points.length];scan(a,b,a.s,b.s||this.length)}for(const br of this.branches){let lengths=[0];for(let i=1;i<br.points.length;i++)lengths.push(lengths.at(-1)+Math.hypot(br.points[i].x-br.points[i-1].x,br.points[i].y-br.points[i-1].y));for(let i=0;i<br.points.length-1;i++)scan(br.points[i],br.points[i+1],(br.from+(br.to-br.from)*lengths[i]/lengths.at(-1))*this.length,(br.from+(br.to-br.from)*lengths[i+1]/lengths.at(-1))*this.length,true)}return best}
 zone(s,key){const t=wrap(s,this.length)/this.length;return (this.data[key]||[]).find(z=>t>=z.from&&t<=z.to)}
 surface(s){return this.zone(s,'surfaces')?.type||'road'}
}
